/*
 * Crossly Buyer API
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;

/**
 * CreateCbxAdCreditSpendResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-09-17T03:09:37.881-04:00[America/New_York]")
public class CreateCbxAdCreditSpendResponse {
  public static final String SERIALIZED_NAME_SPENT_CENTS = "spentCents";
  @SerializedName(SERIALIZED_NAME_SPENT_CENTS)
  private BigDecimal spentCents;

  public static final String SERIALIZED_NAME_SHORTFALL_CENTS = "shortfallCents";
  @SerializedName(SERIALIZED_NAME_SHORTFALL_CENTS)
  private BigDecimal shortfallCents;

  public static final String SERIALIZED_NAME_BALANCE_CENTS = "balanceCents";
  @SerializedName(SERIALIZED_NAME_BALANCE_CENTS)
  private BigDecimal balanceCents;

  public static final String SERIALIZED_NAME_POOL_BASE_UNITS = "poolBaseUnits";
  @SerializedName(SERIALIZED_NAME_POOL_BASE_UNITS)
  private String poolBaseUnits;

  public static final String SERIALIZED_NAME_DUPLICATE = "duplicate";
  @SerializedName(SERIALIZED_NAME_DUPLICATE)
  private Boolean duplicate;

  public CreateCbxAdCreditSpendResponse() { 
  }

  public CreateCbxAdCreditSpendResponse spentCents(BigDecimal spentCents) {
    
    this.spentCents = spentCents;
    return this;
  }

   /**
   * Get spentCents
   * @return spentCents
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public BigDecimal getSpentCents() {
    return spentCents;
  }


  public void setSpentCents(BigDecimal spentCents) {
    this.spentCents = spentCents;
  }


  public CreateCbxAdCreditSpendResponse shortfallCents(BigDecimal shortfallCents) {
    
    this.shortfallCents = shortfallCents;
    return this;
  }

   /**
   * Get shortfallCents
   * @return shortfallCents
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public BigDecimal getShortfallCents() {
    return shortfallCents;
  }


  public void setShortfallCents(BigDecimal shortfallCents) {
    this.shortfallCents = shortfallCents;
  }


  public CreateCbxAdCreditSpendResponse balanceCents(BigDecimal balanceCents) {
    
    this.balanceCents = balanceCents;
    return this;
  }

   /**
   * Get balanceCents
   * @return balanceCents
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public BigDecimal getBalanceCents() {
    return balanceCents;
  }


  public void setBalanceCents(BigDecimal balanceCents) {
    this.balanceCents = balanceCents;
  }


  public CreateCbxAdCreditSpendResponse poolBaseUnits(String poolBaseUnits) {
    
    this.poolBaseUnits = poolBaseUnits;
    return this;
  }

   /**
   * Get poolBaseUnits
   * @return poolBaseUnits
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getPoolBaseUnits() {
    return poolBaseUnits;
  }


  public void setPoolBaseUnits(String poolBaseUnits) {
    this.poolBaseUnits = poolBaseUnits;
  }


  public CreateCbxAdCreditSpendResponse duplicate(Boolean duplicate) {
    
    this.duplicate = duplicate;
    return this;
  }

   /**
   * Get duplicate
   * @return duplicate
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Boolean getDuplicate() {
    return duplicate;
  }


  public void setDuplicate(Boolean duplicate) {
    this.duplicate = duplicate;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateCbxAdCreditSpendResponse createCbxAdCreditSpendResponse = (CreateCbxAdCreditSpendResponse) o;
    return Objects.equals(this.spentCents, createCbxAdCreditSpendResponse.spentCents) &&
        Objects.equals(this.shortfallCents, createCbxAdCreditSpendResponse.shortfallCents) &&
        Objects.equals(this.balanceCents, createCbxAdCreditSpendResponse.balanceCents) &&
        Objects.equals(this.poolBaseUnits, createCbxAdCreditSpendResponse.poolBaseUnits) &&
        Objects.equals(this.duplicate, createCbxAdCreditSpendResponse.duplicate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(spentCents, shortfallCents, balanceCents, poolBaseUnits, duplicate);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateCbxAdCreditSpendResponse {\n");
    sb.append("    spentCents: ").append(toIndentedString(spentCents)).append("\n");
    sb.append("    shortfallCents: ").append(toIndentedString(shortfallCents)).append("\n");
    sb.append("    balanceCents: ").append(toIndentedString(balanceCents)).append("\n");
    sb.append("    poolBaseUnits: ").append(toIndentedString(poolBaseUnits)).append("\n");
    sb.append("    duplicate: ").append(toIndentedString(duplicate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

