/*
 * Crossly Buyer API
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;

/**
 * GetAnalyticBookkeepingResponseMonthlyPL
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-09-17T03:09:37.881-04:00[America/New_York]")
public class GetAnalyticBookkeepingResponseMonthlyPL {
  public static final String SERIALIZED_NAME_MONTH = "month";
  @SerializedName(SERIALIZED_NAME_MONTH)
  private BigDecimal month;

  public static final String SERIALIZED_NAME_REVENUE = "revenue";
  @SerializedName(SERIALIZED_NAME_REVENUE)
  private BigDecimal revenue;

  public static final String SERIALIZED_NAME_COGS = "cogs";
  @SerializedName(SERIALIZED_NAME_COGS)
  private BigDecimal cogs;

  public static final String SERIALIZED_NAME_PLATFORM_FEES = "platformFees";
  @SerializedName(SERIALIZED_NAME_PLATFORM_FEES)
  private BigDecimal platformFees;

  public static final String SERIALIZED_NAME_SHIPPING_COSTS = "shippingCosts";
  @SerializedName(SERIALIZED_NAME_SHIPPING_COSTS)
  private BigDecimal shippingCosts;

  public static final String SERIALIZED_NAME_NET_PROFIT = "netProfit";
  @SerializedName(SERIALIZED_NAME_NET_PROFIT)
  private BigDecimal netProfit;

  public GetAnalyticBookkeepingResponseMonthlyPL() { 
  }

  public GetAnalyticBookkeepingResponseMonthlyPL month(BigDecimal month) {
    
    this.month = month;
    return this;
  }

   /**
   * Get month
   * @return month
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public BigDecimal getMonth() {
    return month;
  }


  public void setMonth(BigDecimal month) {
    this.month = month;
  }


  public GetAnalyticBookkeepingResponseMonthlyPL revenue(BigDecimal revenue) {
    
    this.revenue = revenue;
    return this;
  }

   /**
   * Get revenue
   * @return revenue
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public BigDecimal getRevenue() {
    return revenue;
  }


  public void setRevenue(BigDecimal revenue) {
    this.revenue = revenue;
  }


  public GetAnalyticBookkeepingResponseMonthlyPL cogs(BigDecimal cogs) {
    
    this.cogs = cogs;
    return this;
  }

   /**
   * Get cogs
   * @return cogs
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public BigDecimal getCogs() {
    return cogs;
  }


  public void setCogs(BigDecimal cogs) {
    this.cogs = cogs;
  }


  public GetAnalyticBookkeepingResponseMonthlyPL platformFees(BigDecimal platformFees) {
    
    this.platformFees = platformFees;
    return this;
  }

   /**
   * Get platformFees
   * @return platformFees
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public BigDecimal getPlatformFees() {
    return platformFees;
  }


  public void setPlatformFees(BigDecimal platformFees) {
    this.platformFees = platformFees;
  }


  public GetAnalyticBookkeepingResponseMonthlyPL shippingCosts(BigDecimal shippingCosts) {
    
    this.shippingCosts = shippingCosts;
    return this;
  }

   /**
   * Get shippingCosts
   * @return shippingCosts
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public BigDecimal getShippingCosts() {
    return shippingCosts;
  }


  public void setShippingCosts(BigDecimal shippingCosts) {
    this.shippingCosts = shippingCosts;
  }


  public GetAnalyticBookkeepingResponseMonthlyPL netProfit(BigDecimal netProfit) {
    
    this.netProfit = netProfit;
    return this;
  }

   /**
   * Get netProfit
   * @return netProfit
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public BigDecimal getNetProfit() {
    return netProfit;
  }


  public void setNetProfit(BigDecimal netProfit) {
    this.netProfit = netProfit;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetAnalyticBookkeepingResponseMonthlyPL getAnalyticBookkeepingResponseMonthlyPL = (GetAnalyticBookkeepingResponseMonthlyPL) o;
    return Objects.equals(this.month, getAnalyticBookkeepingResponseMonthlyPL.month) &&
        Objects.equals(this.revenue, getAnalyticBookkeepingResponseMonthlyPL.revenue) &&
        Objects.equals(this.cogs, getAnalyticBookkeepingResponseMonthlyPL.cogs) &&
        Objects.equals(this.platformFees, getAnalyticBookkeepingResponseMonthlyPL.platformFees) &&
        Objects.equals(this.shippingCosts, getAnalyticBookkeepingResponseMonthlyPL.shippingCosts) &&
        Objects.equals(this.netProfit, getAnalyticBookkeepingResponseMonthlyPL.netProfit);
  }

  @Override
  public int hashCode() {
    return Objects.hash(month, revenue, cogs, platformFees, shippingCosts, netProfit);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetAnalyticBookkeepingResponseMonthlyPL {\n");
    sb.append("    month: ").append(toIndentedString(month)).append("\n");
    sb.append("    revenue: ").append(toIndentedString(revenue)).append("\n");
    sb.append("    cogs: ").append(toIndentedString(cogs)).append("\n");
    sb.append("    platformFees: ").append(toIndentedString(platformFees)).append("\n");
    sb.append("    shippingCosts: ").append(toIndentedString(shippingCosts)).append("\n");
    sb.append("    netProfit: ").append(toIndentedString(netProfit)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

