/*
 * Crossly Buyer API
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import org.openapitools.jackson.nullable.JsonNullable;
import org.threeten.bp.OffsetDateTime;

/**
 * GetAnalyticItemResponseItems
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-09-17T03:09:37.881-04:00[America/New_York]")
public class GetAnalyticItemResponseItems {
  public static final String SERIALIZED_NAME_SALE_ID = "saleId";
  @SerializedName(SERIALIZED_NAME_SALE_ID)
  private String saleId;

  public static final String SERIALIZED_NAME_PLATFORM = "platform";
  @SerializedName(SERIALIZED_NAME_PLATFORM)
  private String platform;

  public static final String SERIALIZED_NAME_PLATFORM_ORDER_ID = "platformOrderId";
  @SerializedName(SERIALIZED_NAME_PLATFORM_ORDER_ID)
  private String platformOrderId;

  public static final String SERIALIZED_NAME_ITEM_TITLE = "itemTitle";
  @SerializedName(SERIALIZED_NAME_ITEM_TITLE)
  private String itemTitle;

  public static final String SERIALIZED_NAME_ITEM_BRAND = "itemBrand";
  @SerializedName(SERIALIZED_NAME_ITEM_BRAND)
  private String itemBrand;

  public static final String SERIALIZED_NAME_ITEM_SKU = "itemSku";
  @SerializedName(SERIALIZED_NAME_ITEM_SKU)
  private String itemSku;

  public static final String SERIALIZED_NAME_SALE_PRICE = "salePrice";
  @SerializedName(SERIALIZED_NAME_SALE_PRICE)
  private BigDecimal salePrice;

  public static final String SERIALIZED_NAME_PLATFORM_FEE = "platformFee";
  @SerializedName(SERIALIZED_NAME_PLATFORM_FEE)
  private BigDecimal platformFee;

  public static final String SERIALIZED_NAME_SHIPPING_COST = "shippingCost";
  @SerializedName(SERIALIZED_NAME_SHIPPING_COST)
  private BigDecimal shippingCost;

  public static final String SERIALIZED_NAME_COST_OF_GOODS = "costOfGoods";
  @SerializedName(SERIALIZED_NAME_COST_OF_GOODS)
  private BigDecimal costOfGoods;

  public static final String SERIALIZED_NAME_NET_PROFIT = "netProfit";
  @SerializedName(SERIALIZED_NAME_NET_PROFIT)
  private BigDecimal netProfit;

  public static final String SERIALIZED_NAME_MARGIN_PCT = "marginPct";
  @SerializedName(SERIALIZED_NAME_MARGIN_PCT)
  private BigDecimal marginPct;

  public static final String SERIALIZED_NAME_DAYS_TO_SELL = "daysToSell";
  @SerializedName(SERIALIZED_NAME_DAYS_TO_SELL)
  private BigDecimal daysToSell;

  public static final String SERIALIZED_NAME_DETECTED_AT = "detectedAt";
  @SerializedName(SERIALIZED_NAME_DETECTED_AT)
  private OffsetDateTime detectedAt;

  public GetAnalyticItemResponseItems() { 
  }

  public GetAnalyticItemResponseItems saleId(String saleId) {
    
    this.saleId = saleId;
    return this;
  }

   /**
   * Get saleId
   * @return saleId
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getSaleId() {
    return saleId;
  }


  public void setSaleId(String saleId) {
    this.saleId = saleId;
  }


  public GetAnalyticItemResponseItems platform(String platform) {
    
    this.platform = platform;
    return this;
  }

   /**
   * Get platform
   * @return platform
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getPlatform() {
    return platform;
  }


  public void setPlatform(String platform) {
    this.platform = platform;
  }


  public GetAnalyticItemResponseItems platformOrderId(String platformOrderId) {
    
    this.platformOrderId = platformOrderId;
    return this;
  }

   /**
   * Get platformOrderId
   * @return platformOrderId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getPlatformOrderId() {
    return platformOrderId;
  }


  public void setPlatformOrderId(String platformOrderId) {
    this.platformOrderId = platformOrderId;
  }


  public GetAnalyticItemResponseItems itemTitle(String itemTitle) {
    
    this.itemTitle = itemTitle;
    return this;
  }

   /**
   * Get itemTitle
   * @return itemTitle
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getItemTitle() {
    return itemTitle;
  }


  public void setItemTitle(String itemTitle) {
    this.itemTitle = itemTitle;
  }


  public GetAnalyticItemResponseItems itemBrand(String itemBrand) {
    
    this.itemBrand = itemBrand;
    return this;
  }

   /**
   * Get itemBrand
   * @return itemBrand
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getItemBrand() {
    return itemBrand;
  }


  public void setItemBrand(String itemBrand) {
    this.itemBrand = itemBrand;
  }


  public GetAnalyticItemResponseItems itemSku(String itemSku) {
    
    this.itemSku = itemSku;
    return this;
  }

   /**
   * Get itemSku
   * @return itemSku
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getItemSku() {
    return itemSku;
  }


  public void setItemSku(String itemSku) {
    this.itemSku = itemSku;
  }


  public GetAnalyticItemResponseItems salePrice(BigDecimal salePrice) {
    
    this.salePrice = salePrice;
    return this;
  }

   /**
   * Get salePrice
   * @return salePrice
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BigDecimal getSalePrice() {
    return salePrice;
  }


  public void setSalePrice(BigDecimal salePrice) {
    this.salePrice = salePrice;
  }


  public GetAnalyticItemResponseItems platformFee(BigDecimal platformFee) {
    
    this.platformFee = platformFee;
    return this;
  }

   /**
   * Get platformFee
   * @return platformFee
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BigDecimal getPlatformFee() {
    return platformFee;
  }


  public void setPlatformFee(BigDecimal platformFee) {
    this.platformFee = platformFee;
  }


  public GetAnalyticItemResponseItems shippingCost(BigDecimal shippingCost) {
    
    this.shippingCost = shippingCost;
    return this;
  }

   /**
   * Get shippingCost
   * @return shippingCost
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BigDecimal getShippingCost() {
    return shippingCost;
  }


  public void setShippingCost(BigDecimal shippingCost) {
    this.shippingCost = shippingCost;
  }


  public GetAnalyticItemResponseItems costOfGoods(BigDecimal costOfGoods) {
    
    this.costOfGoods = costOfGoods;
    return this;
  }

   /**
   * Get costOfGoods
   * @return costOfGoods
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BigDecimal getCostOfGoods() {
    return costOfGoods;
  }


  public void setCostOfGoods(BigDecimal costOfGoods) {
    this.costOfGoods = costOfGoods;
  }


  public GetAnalyticItemResponseItems netProfit(BigDecimal netProfit) {
    
    this.netProfit = netProfit;
    return this;
  }

   /**
   * Get netProfit
   * @return netProfit
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BigDecimal getNetProfit() {
    return netProfit;
  }


  public void setNetProfit(BigDecimal netProfit) {
    this.netProfit = netProfit;
  }


  public GetAnalyticItemResponseItems marginPct(BigDecimal marginPct) {
    
    this.marginPct = marginPct;
    return this;
  }

   /**
   * Get marginPct
   * @return marginPct
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public BigDecimal getMarginPct() {
    return marginPct;
  }


  public void setMarginPct(BigDecimal marginPct) {
    this.marginPct = marginPct;
  }


  public GetAnalyticItemResponseItems daysToSell(BigDecimal daysToSell) {
    
    this.daysToSell = daysToSell;
    return this;
  }

   /**
   * Get daysToSell
   * @return daysToSell
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BigDecimal getDaysToSell() {
    return daysToSell;
  }


  public void setDaysToSell(BigDecimal daysToSell) {
    this.daysToSell = daysToSell;
  }


  public GetAnalyticItemResponseItems detectedAt(OffsetDateTime detectedAt) {
    
    this.detectedAt = detectedAt;
    return this;
  }

   /**
   * Get detectedAt
   * @return detectedAt
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public OffsetDateTime getDetectedAt() {
    return detectedAt;
  }


  public void setDetectedAt(OffsetDateTime detectedAt) {
    this.detectedAt = detectedAt;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetAnalyticItemResponseItems getAnalyticItemResponseItems = (GetAnalyticItemResponseItems) o;
    return Objects.equals(this.saleId, getAnalyticItemResponseItems.saleId) &&
        Objects.equals(this.platform, getAnalyticItemResponseItems.platform) &&
        Objects.equals(this.platformOrderId, getAnalyticItemResponseItems.platformOrderId) &&
        Objects.equals(this.itemTitle, getAnalyticItemResponseItems.itemTitle) &&
        Objects.equals(this.itemBrand, getAnalyticItemResponseItems.itemBrand) &&
        Objects.equals(this.itemSku, getAnalyticItemResponseItems.itemSku) &&
        Objects.equals(this.salePrice, getAnalyticItemResponseItems.salePrice) &&
        Objects.equals(this.platformFee, getAnalyticItemResponseItems.platformFee) &&
        Objects.equals(this.shippingCost, getAnalyticItemResponseItems.shippingCost) &&
        Objects.equals(this.costOfGoods, getAnalyticItemResponseItems.costOfGoods) &&
        Objects.equals(this.netProfit, getAnalyticItemResponseItems.netProfit) &&
        Objects.equals(this.marginPct, getAnalyticItemResponseItems.marginPct) &&
        Objects.equals(this.daysToSell, getAnalyticItemResponseItems.daysToSell) &&
        Objects.equals(this.detectedAt, getAnalyticItemResponseItems.detectedAt);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(saleId, platform, platformOrderId, itemTitle, itemBrand, itemSku, salePrice, platformFee, shippingCost, costOfGoods, netProfit, marginPct, daysToSell, detectedAt);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetAnalyticItemResponseItems {\n");
    sb.append("    saleId: ").append(toIndentedString(saleId)).append("\n");
    sb.append("    platform: ").append(toIndentedString(platform)).append("\n");
    sb.append("    platformOrderId: ").append(toIndentedString(platformOrderId)).append("\n");
    sb.append("    itemTitle: ").append(toIndentedString(itemTitle)).append("\n");
    sb.append("    itemBrand: ").append(toIndentedString(itemBrand)).append("\n");
    sb.append("    itemSku: ").append(toIndentedString(itemSku)).append("\n");
    sb.append("    salePrice: ").append(toIndentedString(salePrice)).append("\n");
    sb.append("    platformFee: ").append(toIndentedString(platformFee)).append("\n");
    sb.append("    shippingCost: ").append(toIndentedString(shippingCost)).append("\n");
    sb.append("    costOfGoods: ").append(toIndentedString(costOfGoods)).append("\n");
    sb.append("    netProfit: ").append(toIndentedString(netProfit)).append("\n");
    sb.append("    marginPct: ").append(toIndentedString(marginPct)).append("\n");
    sb.append("    daysToSell: ").append(toIndentedString(daysToSell)).append("\n");
    sb.append("    detectedAt: ").append(toIndentedString(detectedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

