/*
 * Crossly Buyer API
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;

/**
 * GetConnectionHealthResponseExtension
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-09-17T03:09:37.881-04:00[America/New_York]")
public class GetConnectionHealthResponseExtension {
  public static final String SERIALIZED_NAME_ONLINE = "online";
  @SerializedName(SERIALIZED_NAME_ONLINE)
  private Boolean online;

  public static final String SERIALIZED_NAME_LAST_BROWSER_PUSH_AT = "lastBrowserPushAt";
  @SerializedName(SERIALIZED_NAME_LAST_BROWSER_PUSH_AT)
  private String lastBrowserPushAt;

  public static final String SERIALIZED_NAME_LAST_BROWSER_PUSH_AGO = "lastBrowserPushAgo";
  @SerializedName(SERIALIZED_NAME_LAST_BROWSER_PUSH_AGO)
  private String lastBrowserPushAgo;

  public static final String SERIALIZED_NAME_REPORTED_VERSION = "reportedVersion";
  @SerializedName(SERIALIZED_NAME_REPORTED_VERSION)
  private String reportedVersion;

  public GetConnectionHealthResponseExtension() { 
  }

  public GetConnectionHealthResponseExtension online(Boolean online) {
    
    this.online = online;
    return this;
  }

   /**
   * Heartbeat within the last 15 minutes. False is NOT proof of breakage — a closed browser looks the same — so it is always paired with the durable timestamp below.
   * @return online
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "Heartbeat within the last 15 minutes. False is NOT proof of breakage — a closed browser looks the same — so it is always paired with the durable timestamp below.")

  public Boolean getOnline() {
    return online;
  }


  public void setOnline(Boolean online) {
    this.online = online;
  }


  public GetConnectionHealthResponseExtension lastBrowserPushAt(String lastBrowserPushAt) {
    
    this.lastBrowserPushAt = lastBrowserPushAt;
    return this;
  }

   /**
   * Newest browser push across every account. The durable answer to \&quot;when did the extension last do anything\&quot;, surviving a Redis flush.
   * @return lastBrowserPushAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Newest browser push across every account. The durable answer to \"when did the extension last do anything\", surviving a Redis flush.")

  public String getLastBrowserPushAt() {
    return lastBrowserPushAt;
  }


  public void setLastBrowserPushAt(String lastBrowserPushAt) {
    this.lastBrowserPushAt = lastBrowserPushAt;
  }


  public GetConnectionHealthResponseExtension lastBrowserPushAgo(String lastBrowserPushAgo) {
    
    this.lastBrowserPushAgo = lastBrowserPushAgo;
    return this;
  }

   /**
   * Get lastBrowserPushAgo
   * @return lastBrowserPushAgo
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getLastBrowserPushAgo() {
    return lastBrowserPushAgo;
  }


  public void setLastBrowserPushAgo(String lastBrowserPushAgo) {
    this.lastBrowserPushAgo = lastBrowserPushAgo;
  }


  public GetConnectionHealthResponseExtension reportedVersion(String reportedVersion) {
    
    this.reportedVersion = reportedVersion;
    return this;
  }

   /**
   * Highest version any platform&#39;s browser report carried, or null when the extension has never told us (it does not send one today — see the service README notes in routes/extension-health.ts).
   * @return reportedVersion
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Highest version any platform's browser report carried, or null when the extension has never told us (it does not send one today — see the service README notes in routes/extension-health.ts).")

  public String getReportedVersion() {
    return reportedVersion;
  }


  public void setReportedVersion(String reportedVersion) {
    this.reportedVersion = reportedVersion;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetConnectionHealthResponseExtension getConnectionHealthResponseExtension = (GetConnectionHealthResponseExtension) o;
    return Objects.equals(this.online, getConnectionHealthResponseExtension.online) &&
        Objects.equals(this.lastBrowserPushAt, getConnectionHealthResponseExtension.lastBrowserPushAt) &&
        Objects.equals(this.lastBrowserPushAgo, getConnectionHealthResponseExtension.lastBrowserPushAgo) &&
        Objects.equals(this.reportedVersion, getConnectionHealthResponseExtension.reportedVersion);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(online, lastBrowserPushAt, lastBrowserPushAgo, reportedVersion);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetConnectionHealthResponseExtension {\n");
    sb.append("    online: ").append(toIndentedString(online)).append("\n");
    sb.append("    lastBrowserPushAt: ").append(toIndentedString(lastBrowserPushAt)).append("\n");
    sb.append("    lastBrowserPushAgo: ").append(toIndentedString(lastBrowserPushAgo)).append("\n");
    sb.append("    reportedVersion: ").append(toIndentedString(reportedVersion)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

