/*
 * Crossly Buyer API
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.threeten.bp.OffsetDateTime;

/**
 * GetInboxResponseMessages
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-09-17T03:09:37.881-04:00[America/New_York]")
public class GetInboxResponseMessages {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_VIDEO_URL = "videoUrl";
  @SerializedName(SERIALIZED_NAME_VIDEO_URL)
  private String videoUrl;

  public static final String SERIALIZED_NAME_SYNCED_AT = "syncedAt";
  @SerializedName(SERIALIZED_NAME_SYNCED_AT)
  private OffsetDateTime syncedAt;

  public static final String SERIALIZED_NAME_SENT_AT = "sentAt";
  @SerializedName(SERIALIZED_NAME_SENT_AT)
  private OffsetDateTime sentAt;

  public static final String SERIALIZED_NAME_BODY = "body";
  @SerializedName(SERIALIZED_NAME_BODY)
  private String body;

  public static final String SERIALIZED_NAME_CONVERSATION_ID = "conversationId";
  @SerializedName(SERIALIZED_NAME_CONVERSATION_ID)
  private String conversationId;

  public static final String SERIALIZED_NAME_PLATFORM_MESSAGE_ID = "platformMessageId";
  @SerializedName(SERIALIZED_NAME_PLATFORM_MESSAGE_ID)
  private String platformMessageId;

  public static final String SERIALIZED_NAME_SENDER = "sender";
  @SerializedName(SERIALIZED_NAME_SENDER)
  private String sender;

  public static final String SERIALIZED_NAME_ATTACHMENTS = "attachments";
  @SerializedName(SERIALIZED_NAME_ATTACHMENTS)
  private List<String> attachments = null;

  public static final String SERIALIZED_NAME_AI_INTENT = "aiIntent";
  @SerializedName(SERIALIZED_NAME_AI_INTENT)
  private String aiIntent;

  public static final String SERIALIZED_NAME_AI_URGENCY = "aiUrgency";
  @SerializedName(SERIALIZED_NAME_AI_URGENCY)
  private String aiUrgency;

  public static final String SERIALIZED_NAME_AI_SCAM_SCORE = "aiScamScore";
  @SerializedName(SERIALIZED_NAME_AI_SCAM_SCORE)
  private BigDecimal aiScamScore;

  public static final String SERIALIZED_NAME_AI_SUGGESTED_REPLY = "aiSuggestedReply";
  @SerializedName(SERIALIZED_NAME_AI_SUGGESTED_REPLY)
  private String aiSuggestedReply;

  public static final String SERIALIZED_NAME_AI_TRIAGED_AT = "aiTriagedAt";
  @SerializedName(SERIALIZED_NAME_AI_TRIAGED_AT)
  private OffsetDateTime aiTriagedAt;

  public static final String SERIALIZED_NAME_STICKER_ID = "stickerId";
  @SerializedName(SERIALIZED_NAME_STICKER_ID)
  private String stickerId;

  public static final String SERIALIZED_NAME_GIF_URL = "gifUrl";
  @SerializedName(SERIALIZED_NAME_GIF_URL)
  private String gifUrl;

  public static final String SERIALIZED_NAME_VIDEO_THUMB_URL = "videoThumbUrl";
  @SerializedName(SERIALIZED_NAME_VIDEO_THUMB_URL)
  private String videoThumbUrl;

  public static final String SERIALIZED_NAME_VOICE_URL = "voiceUrl";
  @SerializedName(SERIALIZED_NAME_VOICE_URL)
  private String voiceUrl;

  public static final String SERIALIZED_NAME_VOICE_DURATION_SECONDS = "voiceDurationSeconds";
  @SerializedName(SERIALIZED_NAME_VOICE_DURATION_SECONDS)
  private BigDecimal voiceDurationSeconds;

  public GetInboxResponseMessages() { 
  }

  public GetInboxResponseMessages id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getId() {
    return id;
  }


  public void setId(String id) {
    this.id = id;
  }


  public GetInboxResponseMessages videoUrl(String videoUrl) {
    
    this.videoUrl = videoUrl;
    return this;
  }

   /**
   * Get videoUrl
   * @return videoUrl
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getVideoUrl() {
    return videoUrl;
  }


  public void setVideoUrl(String videoUrl) {
    this.videoUrl = videoUrl;
  }


  public GetInboxResponseMessages syncedAt(OffsetDateTime syncedAt) {
    
    this.syncedAt = syncedAt;
    return this;
  }

   /**
   * Get syncedAt
   * @return syncedAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public OffsetDateTime getSyncedAt() {
    return syncedAt;
  }


  public void setSyncedAt(OffsetDateTime syncedAt) {
    this.syncedAt = syncedAt;
  }


  public GetInboxResponseMessages sentAt(OffsetDateTime sentAt) {
    
    this.sentAt = sentAt;
    return this;
  }

   /**
   * Get sentAt
   * @return sentAt
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public OffsetDateTime getSentAt() {
    return sentAt;
  }


  public void setSentAt(OffsetDateTime sentAt) {
    this.sentAt = sentAt;
  }


  public GetInboxResponseMessages body(String body) {
    
    this.body = body;
    return this;
  }

   /**
   * Get body
   * @return body
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getBody() {
    return body;
  }


  public void setBody(String body) {
    this.body = body;
  }


  public GetInboxResponseMessages conversationId(String conversationId) {
    
    this.conversationId = conversationId;
    return this;
  }

   /**
   * Get conversationId
   * @return conversationId
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getConversationId() {
    return conversationId;
  }


  public void setConversationId(String conversationId) {
    this.conversationId = conversationId;
  }


  public GetInboxResponseMessages platformMessageId(String platformMessageId) {
    
    this.platformMessageId = platformMessageId;
    return this;
  }

   /**
   * Get platformMessageId
   * @return platformMessageId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getPlatformMessageId() {
    return platformMessageId;
  }


  public void setPlatformMessageId(String platformMessageId) {
    this.platformMessageId = platformMessageId;
  }


  public GetInboxResponseMessages sender(String sender) {
    
    this.sender = sender;
    return this;
  }

   /**
   * Get sender
   * @return sender
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getSender() {
    return sender;
  }


  public void setSender(String sender) {
    this.sender = sender;
  }


  public GetInboxResponseMessages attachments(List<String> attachments) {
    
    this.attachments = attachments;
    return this;
  }

  public GetInboxResponseMessages addAttachmentsItem(String attachmentsItem) {
    if (this.attachments == null) {
      this.attachments = new ArrayList<String>();
    }
    this.attachments.add(attachmentsItem);
    return this;
  }

   /**
   * Get attachments
   * @return attachments
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<String> getAttachments() {
    return attachments;
  }


  public void setAttachments(List<String> attachments) {
    this.attachments = attachments;
  }


  public GetInboxResponseMessages aiIntent(String aiIntent) {
    
    this.aiIntent = aiIntent;
    return this;
  }

   /**
   * Get aiIntent
   * @return aiIntent
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getAiIntent() {
    return aiIntent;
  }


  public void setAiIntent(String aiIntent) {
    this.aiIntent = aiIntent;
  }


  public GetInboxResponseMessages aiUrgency(String aiUrgency) {
    
    this.aiUrgency = aiUrgency;
    return this;
  }

   /**
   * Get aiUrgency
   * @return aiUrgency
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getAiUrgency() {
    return aiUrgency;
  }


  public void setAiUrgency(String aiUrgency) {
    this.aiUrgency = aiUrgency;
  }


  public GetInboxResponseMessages aiScamScore(BigDecimal aiScamScore) {
    
    this.aiScamScore = aiScamScore;
    return this;
  }

   /**
   * Get aiScamScore
   * @return aiScamScore
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BigDecimal getAiScamScore() {
    return aiScamScore;
  }


  public void setAiScamScore(BigDecimal aiScamScore) {
    this.aiScamScore = aiScamScore;
  }


  public GetInboxResponseMessages aiSuggestedReply(String aiSuggestedReply) {
    
    this.aiSuggestedReply = aiSuggestedReply;
    return this;
  }

   /**
   * Get aiSuggestedReply
   * @return aiSuggestedReply
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getAiSuggestedReply() {
    return aiSuggestedReply;
  }


  public void setAiSuggestedReply(String aiSuggestedReply) {
    this.aiSuggestedReply = aiSuggestedReply;
  }


  public GetInboxResponseMessages aiTriagedAt(OffsetDateTime aiTriagedAt) {
    
    this.aiTriagedAt = aiTriagedAt;
    return this;
  }

   /**
   * Get aiTriagedAt
   * @return aiTriagedAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public OffsetDateTime getAiTriagedAt() {
    return aiTriagedAt;
  }


  public void setAiTriagedAt(OffsetDateTime aiTriagedAt) {
    this.aiTriagedAt = aiTriagedAt;
  }


  public GetInboxResponseMessages stickerId(String stickerId) {
    
    this.stickerId = stickerId;
    return this;
  }

   /**
   * Get stickerId
   * @return stickerId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getStickerId() {
    return stickerId;
  }


  public void setStickerId(String stickerId) {
    this.stickerId = stickerId;
  }


  public GetInboxResponseMessages gifUrl(String gifUrl) {
    
    this.gifUrl = gifUrl;
    return this;
  }

   /**
   * Get gifUrl
   * @return gifUrl
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getGifUrl() {
    return gifUrl;
  }


  public void setGifUrl(String gifUrl) {
    this.gifUrl = gifUrl;
  }


  public GetInboxResponseMessages videoThumbUrl(String videoThumbUrl) {
    
    this.videoThumbUrl = videoThumbUrl;
    return this;
  }

   /**
   * Get videoThumbUrl
   * @return videoThumbUrl
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getVideoThumbUrl() {
    return videoThumbUrl;
  }


  public void setVideoThumbUrl(String videoThumbUrl) {
    this.videoThumbUrl = videoThumbUrl;
  }


  public GetInboxResponseMessages voiceUrl(String voiceUrl) {
    
    this.voiceUrl = voiceUrl;
    return this;
  }

   /**
   * Get voiceUrl
   * @return voiceUrl
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getVoiceUrl() {
    return voiceUrl;
  }


  public void setVoiceUrl(String voiceUrl) {
    this.voiceUrl = voiceUrl;
  }


  public GetInboxResponseMessages voiceDurationSeconds(BigDecimal voiceDurationSeconds) {
    
    this.voiceDurationSeconds = voiceDurationSeconds;
    return this;
  }

   /**
   * Get voiceDurationSeconds
   * @return voiceDurationSeconds
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BigDecimal getVoiceDurationSeconds() {
    return voiceDurationSeconds;
  }


  public void setVoiceDurationSeconds(BigDecimal voiceDurationSeconds) {
    this.voiceDurationSeconds = voiceDurationSeconds;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetInboxResponseMessages getInboxResponseMessages = (GetInboxResponseMessages) o;
    return Objects.equals(this.id, getInboxResponseMessages.id) &&
        Objects.equals(this.videoUrl, getInboxResponseMessages.videoUrl) &&
        Objects.equals(this.syncedAt, getInboxResponseMessages.syncedAt) &&
        Objects.equals(this.sentAt, getInboxResponseMessages.sentAt) &&
        Objects.equals(this.body, getInboxResponseMessages.body) &&
        Objects.equals(this.conversationId, getInboxResponseMessages.conversationId) &&
        Objects.equals(this.platformMessageId, getInboxResponseMessages.platformMessageId) &&
        Objects.equals(this.sender, getInboxResponseMessages.sender) &&
        Objects.equals(this.attachments, getInboxResponseMessages.attachments) &&
        Objects.equals(this.aiIntent, getInboxResponseMessages.aiIntent) &&
        Objects.equals(this.aiUrgency, getInboxResponseMessages.aiUrgency) &&
        Objects.equals(this.aiScamScore, getInboxResponseMessages.aiScamScore) &&
        Objects.equals(this.aiSuggestedReply, getInboxResponseMessages.aiSuggestedReply) &&
        Objects.equals(this.aiTriagedAt, getInboxResponseMessages.aiTriagedAt) &&
        Objects.equals(this.stickerId, getInboxResponseMessages.stickerId) &&
        Objects.equals(this.gifUrl, getInboxResponseMessages.gifUrl) &&
        Objects.equals(this.videoThumbUrl, getInboxResponseMessages.videoThumbUrl) &&
        Objects.equals(this.voiceUrl, getInboxResponseMessages.voiceUrl) &&
        Objects.equals(this.voiceDurationSeconds, getInboxResponseMessages.voiceDurationSeconds);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, videoUrl, syncedAt, sentAt, body, conversationId, platformMessageId, sender, attachments, aiIntent, aiUrgency, aiScamScore, aiSuggestedReply, aiTriagedAt, stickerId, gifUrl, videoThumbUrl, voiceUrl, voiceDurationSeconds);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetInboxResponseMessages {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    videoUrl: ").append(toIndentedString(videoUrl)).append("\n");
    sb.append("    syncedAt: ").append(toIndentedString(syncedAt)).append("\n");
    sb.append("    sentAt: ").append(toIndentedString(sentAt)).append("\n");
    sb.append("    body: ").append(toIndentedString(body)).append("\n");
    sb.append("    conversationId: ").append(toIndentedString(conversationId)).append("\n");
    sb.append("    platformMessageId: ").append(toIndentedString(platformMessageId)).append("\n");
    sb.append("    sender: ").append(toIndentedString(sender)).append("\n");
    sb.append("    attachments: ").append(toIndentedString(attachments)).append("\n");
    sb.append("    aiIntent: ").append(toIndentedString(aiIntent)).append("\n");
    sb.append("    aiUrgency: ").append(toIndentedString(aiUrgency)).append("\n");
    sb.append("    aiScamScore: ").append(toIndentedString(aiScamScore)).append("\n");
    sb.append("    aiSuggestedReply: ").append(toIndentedString(aiSuggestedReply)).append("\n");
    sb.append("    aiTriagedAt: ").append(toIndentedString(aiTriagedAt)).append("\n");
    sb.append("    stickerId: ").append(toIndentedString(stickerId)).append("\n");
    sb.append("    gifUrl: ").append(toIndentedString(gifUrl)).append("\n");
    sb.append("    videoThumbUrl: ").append(toIndentedString(videoThumbUrl)).append("\n");
    sb.append("    voiceUrl: ").append(toIndentedString(voiceUrl)).append("\n");
    sb.append("    voiceDurationSeconds: ").append(toIndentedString(voiceDurationSeconds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

