/*
 * Crossly Buyer API
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.threeten.bp.OffsetDateTime;

/**
 * ListMeTemplatesItem
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-09-17T03:09:37.881-04:00[America/New_York]")
public class ListMeTemplatesItem {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_BRAND = "brand";
  @SerializedName(SERIALIZED_NAME_BRAND)
  private String brand;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_CREATED_AT = "createdAt";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  private OffsetDateTime createdAt;

  public static final String SERIALIZED_NAME_UPDATED_AT = "updatedAt";
  @SerializedName(SERIALIZED_NAME_UPDATED_AT)
  private OffsetDateTime updatedAt;

  public static final String SERIALIZED_NAME_USER_ID = "userId";
  @SerializedName(SERIALIZED_NAME_USER_ID)
  private String userId;

  public static final String SERIALIZED_NAME_CONDITION = "condition";
  @SerializedName(SERIALIZED_NAME_CONDITION)
  private String condition;

  public static final String SERIALIZED_NAME_SIZE = "size";
  @SerializedName(SERIALIZED_NAME_SIZE)
  private String size;

  public static final String SERIALIZED_NAME_MATERIAL = "material";
  @SerializedName(SERIALIZED_NAME_MATERIAL)
  private String material;

  public static final String SERIALIZED_NAME_STYLE = "style";
  @SerializedName(SERIALIZED_NAME_STYLE)
  private String style;

  public static final String SERIALIZED_NAME_PATTERN = "pattern";
  @SerializedName(SERIALIZED_NAME_PATTERN)
  private String pattern;

  public static final String SERIALIZED_NAME_DEPARTMENT = "department";
  @SerializedName(SERIALIZED_NAME_DEPARTMENT)
  private String department;

  public static final String SERIALIZED_NAME_GENDER = "gender";
  @SerializedName(SERIALIZED_NAME_GENDER)
  private String gender;

  public static final String SERIALIZED_NAME_ITEM_TYPE = "itemType";
  @SerializedName(SERIALIZED_NAME_ITEM_TYPE)
  private String itemType;

  public static final String SERIALIZED_NAME_SIZE_SYSTEM = "sizeSystem";
  @SerializedName(SERIALIZED_NAME_SIZE_SYSTEM)
  private String sizeSystem;

  public static final String SERIALIZED_NAME_COLOR = "color";
  @SerializedName(SERIALIZED_NAME_COLOR)
  private String color;

  public static final String SERIALIZED_NAME_TAGS = "tags";
  @SerializedName(SERIALIZED_NAME_TAGS)
  private List<String> tags = null;

  public static final String SERIALIZED_NAME_NOTES = "notes";
  @SerializedName(SERIALIZED_NAME_NOTES)
  private String notes;

  public static final String SERIALIZED_NAME_WEIGHT_OZ = "weightOz";
  @SerializedName(SERIALIZED_NAME_WEIGHT_OZ)
  private BigDecimal weightOz;

  public static final String SERIALIZED_NAME_IS_DEFAULT = "isDefault";
  @SerializedName(SERIALIZED_NAME_IS_DEFAULT)
  private Boolean isDefault;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  private String description;

  public static final String SERIALIZED_NAME_TITLE = "title";
  @SerializedName(SERIALIZED_NAME_TITLE)
  private String title;

  public static final String SERIALIZED_NAME_SCOPE = "scope";
  @SerializedName(SERIALIZED_NAME_SCOPE)
  private String scope;

  public static final String SERIALIZED_NAME_SHARE_TOKEN = "shareToken";
  @SerializedName(SERIALIZED_NAME_SHARE_TOKEN)
  private String shareToken;

  public static final String SERIALIZED_NAME_DESCRIPTION_VARIANTS = "descriptionVariants";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION_VARIANTS)
  private List<String> descriptionVariants = null;

  public static final String SERIALIZED_NAME_TITLE_VARIANTS = "titleVariants";
  @SerializedName(SERIALIZED_NAME_TITLE_VARIANTS)
  private List<String> titleVariants = null;

  public static final String SERIALIZED_NAME_DEFAULT_FOR_CATEGORY = "defaultForCategory";
  @SerializedName(SERIALIZED_NAME_DEFAULT_FOR_CATEGORY)
  private String defaultForCategory;

  public static final String SERIALIZED_NAME_SORT_ORDER = "sortOrder";
  @SerializedName(SERIALIZED_NAME_SORT_ORDER)
  private BigDecimal sortOrder;

  public ListMeTemplatesItem() { 
  }

  public ListMeTemplatesItem id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getId() {
    return id;
  }


  public void setId(String id) {
    this.id = id;
  }


  public ListMeTemplatesItem brand(String brand) {
    
    this.brand = brand;
    return this;
  }

   /**
   * Get brand
   * @return brand
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getBrand() {
    return brand;
  }


  public void setBrand(String brand) {
    this.brand = brand;
  }


  public ListMeTemplatesItem name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public ListMeTemplatesItem createdAt(OffsetDateTime createdAt) {
    
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }


  public void setCreatedAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public ListMeTemplatesItem updatedAt(OffsetDateTime updatedAt) {
    
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * Get updatedAt
   * @return updatedAt
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }


  public void setUpdatedAt(OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
  }


  public ListMeTemplatesItem userId(String userId) {
    
    this.userId = userId;
    return this;
  }

   /**
   * Get userId
   * @return userId
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getUserId() {
    return userId;
  }


  public void setUserId(String userId) {
    this.userId = userId;
  }


  public ListMeTemplatesItem condition(String condition) {
    
    this.condition = condition;
    return this;
  }

   /**
   * Get condition
   * @return condition
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getCondition() {
    return condition;
  }


  public void setCondition(String condition) {
    this.condition = condition;
  }


  public ListMeTemplatesItem size(String size) {
    
    this.size = size;
    return this;
  }

   /**
   * Get size
   * @return size
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getSize() {
    return size;
  }


  public void setSize(String size) {
    this.size = size;
  }


  public ListMeTemplatesItem material(String material) {
    
    this.material = material;
    return this;
  }

   /**
   * Get material
   * @return material
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getMaterial() {
    return material;
  }


  public void setMaterial(String material) {
    this.material = material;
  }


  public ListMeTemplatesItem style(String style) {
    
    this.style = style;
    return this;
  }

   /**
   * Get style
   * @return style
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getStyle() {
    return style;
  }


  public void setStyle(String style) {
    this.style = style;
  }


  public ListMeTemplatesItem pattern(String pattern) {
    
    this.pattern = pattern;
    return this;
  }

   /**
   * Get pattern
   * @return pattern
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getPattern() {
    return pattern;
  }


  public void setPattern(String pattern) {
    this.pattern = pattern;
  }


  public ListMeTemplatesItem department(String department) {
    
    this.department = department;
    return this;
  }

   /**
   * Get department
   * @return department
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getDepartment() {
    return department;
  }


  public void setDepartment(String department) {
    this.department = department;
  }


  public ListMeTemplatesItem gender(String gender) {
    
    this.gender = gender;
    return this;
  }

   /**
   * Get gender
   * @return gender
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getGender() {
    return gender;
  }


  public void setGender(String gender) {
    this.gender = gender;
  }


  public ListMeTemplatesItem itemType(String itemType) {
    
    this.itemType = itemType;
    return this;
  }

   /**
   * Get itemType
   * @return itemType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getItemType() {
    return itemType;
  }


  public void setItemType(String itemType) {
    this.itemType = itemType;
  }


  public ListMeTemplatesItem sizeSystem(String sizeSystem) {
    
    this.sizeSystem = sizeSystem;
    return this;
  }

   /**
   * Get sizeSystem
   * @return sizeSystem
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getSizeSystem() {
    return sizeSystem;
  }


  public void setSizeSystem(String sizeSystem) {
    this.sizeSystem = sizeSystem;
  }


  public ListMeTemplatesItem color(String color) {
    
    this.color = color;
    return this;
  }

   /**
   * Get color
   * @return color
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getColor() {
    return color;
  }


  public void setColor(String color) {
    this.color = color;
  }


  public ListMeTemplatesItem tags(List<String> tags) {
    
    this.tags = tags;
    return this;
  }

  public ListMeTemplatesItem addTagsItem(String tagsItem) {
    if (this.tags == null) {
      this.tags = new ArrayList<String>();
    }
    this.tags.add(tagsItem);
    return this;
  }

   /**
   * Get tags
   * @return tags
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<String> getTags() {
    return tags;
  }


  public void setTags(List<String> tags) {
    this.tags = tags;
  }


  public ListMeTemplatesItem notes(String notes) {
    
    this.notes = notes;
    return this;
  }

   /**
   * Get notes
   * @return notes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getNotes() {
    return notes;
  }


  public void setNotes(String notes) {
    this.notes = notes;
  }


  public ListMeTemplatesItem weightOz(BigDecimal weightOz) {
    
    this.weightOz = weightOz;
    return this;
  }

   /**
   * Get weightOz
   * @return weightOz
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BigDecimal getWeightOz() {
    return weightOz;
  }


  public void setWeightOz(BigDecimal weightOz) {
    this.weightOz = weightOz;
  }


  public ListMeTemplatesItem isDefault(Boolean isDefault) {
    
    this.isDefault = isDefault;
    return this;
  }

   /**
   * Get isDefault
   * @return isDefault
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Boolean getIsDefault() {
    return isDefault;
  }


  public void setIsDefault(Boolean isDefault) {
    this.isDefault = isDefault;
  }


  public ListMeTemplatesItem description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getDescription() {
    return description;
  }


  public void setDescription(String description) {
    this.description = description;
  }


  public ListMeTemplatesItem title(String title) {
    
    this.title = title;
    return this;
  }

   /**
   * Get title
   * @return title
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getTitle() {
    return title;
  }


  public void setTitle(String title) {
    this.title = title;
  }


  public ListMeTemplatesItem scope(String scope) {
    
    this.scope = scope;
    return this;
  }

   /**
   * Get scope
   * @return scope
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getScope() {
    return scope;
  }


  public void setScope(String scope) {
    this.scope = scope;
  }


  public ListMeTemplatesItem shareToken(String shareToken) {
    
    this.shareToken = shareToken;
    return this;
  }

   /**
   * Get shareToken
   * @return shareToken
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getShareToken() {
    return shareToken;
  }


  public void setShareToken(String shareToken) {
    this.shareToken = shareToken;
  }


  public ListMeTemplatesItem descriptionVariants(List<String> descriptionVariants) {
    
    this.descriptionVariants = descriptionVariants;
    return this;
  }

  public ListMeTemplatesItem addDescriptionVariantsItem(String descriptionVariantsItem) {
    if (this.descriptionVariants == null) {
      this.descriptionVariants = new ArrayList<String>();
    }
    this.descriptionVariants.add(descriptionVariantsItem);
    return this;
  }

   /**
   * Get descriptionVariants
   * @return descriptionVariants
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<String> getDescriptionVariants() {
    return descriptionVariants;
  }


  public void setDescriptionVariants(List<String> descriptionVariants) {
    this.descriptionVariants = descriptionVariants;
  }


  public ListMeTemplatesItem titleVariants(List<String> titleVariants) {
    
    this.titleVariants = titleVariants;
    return this;
  }

  public ListMeTemplatesItem addTitleVariantsItem(String titleVariantsItem) {
    if (this.titleVariants == null) {
      this.titleVariants = new ArrayList<String>();
    }
    this.titleVariants.add(titleVariantsItem);
    return this;
  }

   /**
   * Get titleVariants
   * @return titleVariants
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<String> getTitleVariants() {
    return titleVariants;
  }


  public void setTitleVariants(List<String> titleVariants) {
    this.titleVariants = titleVariants;
  }


  public ListMeTemplatesItem defaultForCategory(String defaultForCategory) {
    
    this.defaultForCategory = defaultForCategory;
    return this;
  }

   /**
   * Get defaultForCategory
   * @return defaultForCategory
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getDefaultForCategory() {
    return defaultForCategory;
  }


  public void setDefaultForCategory(String defaultForCategory) {
    this.defaultForCategory = defaultForCategory;
  }


  public ListMeTemplatesItem sortOrder(BigDecimal sortOrder) {
    
    this.sortOrder = sortOrder;
    return this;
  }

   /**
   * Get sortOrder
   * @return sortOrder
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public BigDecimal getSortOrder() {
    return sortOrder;
  }


  public void setSortOrder(BigDecimal sortOrder) {
    this.sortOrder = sortOrder;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ListMeTemplatesItem listMeTemplatesItem = (ListMeTemplatesItem) o;
    return Objects.equals(this.id, listMeTemplatesItem.id) &&
        Objects.equals(this.brand, listMeTemplatesItem.brand) &&
        Objects.equals(this.name, listMeTemplatesItem.name) &&
        Objects.equals(this.createdAt, listMeTemplatesItem.createdAt) &&
        Objects.equals(this.updatedAt, listMeTemplatesItem.updatedAt) &&
        Objects.equals(this.userId, listMeTemplatesItem.userId) &&
        Objects.equals(this.condition, listMeTemplatesItem.condition) &&
        Objects.equals(this.size, listMeTemplatesItem.size) &&
        Objects.equals(this.material, listMeTemplatesItem.material) &&
        Objects.equals(this.style, listMeTemplatesItem.style) &&
        Objects.equals(this.pattern, listMeTemplatesItem.pattern) &&
        Objects.equals(this.department, listMeTemplatesItem.department) &&
        Objects.equals(this.gender, listMeTemplatesItem.gender) &&
        Objects.equals(this.itemType, listMeTemplatesItem.itemType) &&
        Objects.equals(this.sizeSystem, listMeTemplatesItem.sizeSystem) &&
        Objects.equals(this.color, listMeTemplatesItem.color) &&
        Objects.equals(this.tags, listMeTemplatesItem.tags) &&
        Objects.equals(this.notes, listMeTemplatesItem.notes) &&
        Objects.equals(this.weightOz, listMeTemplatesItem.weightOz) &&
        Objects.equals(this.isDefault, listMeTemplatesItem.isDefault) &&
        Objects.equals(this.description, listMeTemplatesItem.description) &&
        Objects.equals(this.title, listMeTemplatesItem.title) &&
        Objects.equals(this.scope, listMeTemplatesItem.scope) &&
        Objects.equals(this.shareToken, listMeTemplatesItem.shareToken) &&
        Objects.equals(this.descriptionVariants, listMeTemplatesItem.descriptionVariants) &&
        Objects.equals(this.titleVariants, listMeTemplatesItem.titleVariants) &&
        Objects.equals(this.defaultForCategory, listMeTemplatesItem.defaultForCategory) &&
        Objects.equals(this.sortOrder, listMeTemplatesItem.sortOrder);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, brand, name, createdAt, updatedAt, userId, condition, size, material, style, pattern, department, gender, itemType, sizeSystem, color, tags, notes, weightOz, isDefault, description, title, scope, shareToken, descriptionVariants, titleVariants, defaultForCategory, sortOrder);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ListMeTemplatesItem {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    brand: ").append(toIndentedString(brand)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    condition: ").append(toIndentedString(condition)).append("\n");
    sb.append("    size: ").append(toIndentedString(size)).append("\n");
    sb.append("    material: ").append(toIndentedString(material)).append("\n");
    sb.append("    style: ").append(toIndentedString(style)).append("\n");
    sb.append("    pattern: ").append(toIndentedString(pattern)).append("\n");
    sb.append("    department: ").append(toIndentedString(department)).append("\n");
    sb.append("    gender: ").append(toIndentedString(gender)).append("\n");
    sb.append("    itemType: ").append(toIndentedString(itemType)).append("\n");
    sb.append("    sizeSystem: ").append(toIndentedString(sizeSystem)).append("\n");
    sb.append("    color: ").append(toIndentedString(color)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    notes: ").append(toIndentedString(notes)).append("\n");
    sb.append("    weightOz: ").append(toIndentedString(weightOz)).append("\n");
    sb.append("    isDefault: ").append(toIndentedString(isDefault)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    scope: ").append(toIndentedString(scope)).append("\n");
    sb.append("    shareToken: ").append(toIndentedString(shareToken)).append("\n");
    sb.append("    descriptionVariants: ").append(toIndentedString(descriptionVariants)).append("\n");
    sb.append("    titleVariants: ").append(toIndentedString(titleVariants)).append("\n");
    sb.append("    defaultForCategory: ").append(toIndentedString(defaultForCategory)).append("\n");
    sb.append("    sortOrder: ").append(toIndentedString(sortOrder)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

