/*
 * Crossly Seller API
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.CreateCbxRevenueSweepResponseBreakdown;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for CreateCbxRevenueSweepResponse
 */
public class CreateCbxRevenueSweepResponseTest {
    private final CreateCbxRevenueSweepResponse model = new CreateCbxRevenueSweepResponse();

    /**
     * Model tests for CreateCbxRevenueSweepResponse
     */
    @Test
    public void testCreateCbxRevenueSweepResponse() {
        // TODO: test CreateCbxRevenueSweepResponse
    }

    /**
     * Test the property 'swept'
     */
    @Test
    public void sweptTest() {
        // TODO: test swept
    }

    /**
     * Test the property 'baseUnits'
     */
    @Test
    public void baseUnitsTest() {
        // TODO: test baseUnits
    }

    /**
     * Test the property 'txSig'
     */
    @Test
    public void txSigTest() {
        // TODO: test txSig
    }

    /**
     * Test the property 'reason'
     */
    @Test
    public void reasonTest() {
        // TODO: test reason
    }

    /**
     * Test the property 'breakdown'
     */
    @Test
    public void breakdownTest() {
        // TODO: test breakdown
    }

}
