/*
 * Crossly Seller API
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.GetAdOffsiteResponseTerms;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for GetAdOffsiteResponse
 */
public class GetAdOffsiteResponseTest {
    private final GetAdOffsiteResponse model = new GetAdOffsiteResponse();

    /**
     * Model tests for GetAdOffsiteResponse
     */
    @Test
    public void testGetAdOffsiteResponse() {
        // TODO: test GetAdOffsiteResponse
    }

    /**
     * Test the property 'enabled'
     */
    @Test
    public void enabledTest() {
        // TODO: test enabled
    }

    /**
     * Test the property 'maxOffsiteShareBps'
     */
    @Test
    public void maxOffsiteShareBpsTest() {
        // TODO: test maxOffsiteShareBps
    }

    /**
     * Test the property 'minReturnBps'
     */
    @Test
    public void minReturnBpsTest() {
        // TODO: test minReturnBps
    }

    /**
     * Test the property 'returnWindowDays'
     */
    @Test
    public void returnWindowDaysTest() {
        // TODO: test returnWindowDays
    }

    /**
     * Test the property 'allowedNetworks'
     */
    @Test
    public void allowedNetworksTest() {
        // TODO: test allowedNetworks
    }

    /**
     * Test the property 'autoPausedAt'
     */
    @Test
    public void autoPausedAtTest() {
        // TODO: test autoPausedAt
    }

    /**
     * Test the property 'autoPausedReason'
     */
    @Test
    public void autoPausedReasonTest() {
        // TODO: test autoPausedReason
    }

    /**
     * Test the property 'optedInAt'
     */
    @Test
    public void optedInAtTest() {
        // TODO: test optedInAt
    }

    /**
     * Test the property 'terms'
     */
    @Test
    public void termsTest() {
        // TODO: test terms
    }

    /**
     * Test the property 'networkWired'
     */
    @Test
    public void networkWiredTest() {
        // TODO: test networkWired
    }

}
