/*
 * Crossly Seller API
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for GetCbxMeResponseTerms
 */
public class GetCbxMeResponseTermsTest {
    private final GetCbxMeResponseTerms model = new GetCbxMeResponseTerms();

    /**
     * Model tests for GetCbxMeResponseTerms
     */
    @Test
    public void testGetCbxMeResponseTerms() {
        // TODO: test GetCbxMeResponseTerms
    }

    /**
     * Test the property 'earnRateBps'
     */
    @Test
    public void earnRateBpsTest() {
        // TODO: test earnRateBps
    }

    /**
     * Test the property 'purchaseMaturationDays'
     */
    @Test
    public void purchaseMaturationDaysTest() {
        // TODO: test purchaseMaturationDays
    }

    /**
     * Test the property 'claimMinCents'
     */
    @Test
    public void claimMinCentsTest() {
        // TODO: test claimMinCents
    }

    /**
     * Test the property 'withdrawalFeeBps'
     */
    @Test
    public void withdrawalFeeBpsTest() {
        // TODO: test withdrawalFeeBps
    }

    /**
     * Test the property 'withdrawalFeeMinCents'
     */
    @Test
    public void withdrawalFeeMinCentsTest() {
        // TODO: test withdrawalFeeMinCents
    }

    /**
     * Test the property 'withdrawalFeeMaxCents'
     */
    @Test
    public void withdrawalFeeMaxCentsTest() {
        // TODO: test withdrawalFeeMaxCents
    }

    /**
     * Test the property 'inactivityExpiryDays'
     */
    @Test
    public void inactivityExpiryDaysTest() {
        // TODO: test inactivityExpiryDays
    }

    /**
     * Test the property 'claimsEnabled'
     */
    @Test
    public void claimsEnabledTest() {
        // TODO: test claimsEnabled
    }

}
