/*
 * Crossly Seller API
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for GetConnectionHealthResponseExtension
 */
public class GetConnectionHealthResponseExtensionTest {
    private final GetConnectionHealthResponseExtension model = new GetConnectionHealthResponseExtension();

    /**
     * Model tests for GetConnectionHealthResponseExtension
     */
    @Test
    public void testGetConnectionHealthResponseExtension() {
        // TODO: test GetConnectionHealthResponseExtension
    }

    /**
     * Test the property 'online'
     */
    @Test
    public void onlineTest() {
        // TODO: test online
    }

    /**
     * Test the property 'lastBrowserPushAt'
     */
    @Test
    public void lastBrowserPushAtTest() {
        // TODO: test lastBrowserPushAt
    }

    /**
     * Test the property 'lastBrowserPushAgo'
     */
    @Test
    public void lastBrowserPushAgoTest() {
        // TODO: test lastBrowserPushAgo
    }

    /**
     * Test the property 'reportedVersion'
     */
    @Test
    public void reportedVersionTest() {
        // TODO: test reportedVersion
    }

}
