/*
 * Crossly Seller API
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.GetCategoryResponseMain;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for GetCategoryResponse
 */
public class GetCategoryResponseTest {
    private final GetCategoryResponse model = new GetCategoryResponse();

    /**
     * Model tests for GetCategoryResponse
     */
    @Test
    public void testGetCategoryResponse() {
        // TODO: test GetCategoryResponse
    }

    /**
     * Test the property 'main'
     */
    @Test
    public void mainTest() {
        // TODO: test main
    }

    /**
     * Test the property 'sub'
     */
    @Test
    public void subTest() {
        // TODO: test sub
    }

}
