/*
 * Crossly Seller API
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import org.openapitools.jackson.nullable.JsonNullable;
import org.threeten.bp.OffsetDateTime;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for GetMarketProductResponseVariants
 */
public class GetMarketProductResponseVariantsTest {
    private final GetMarketProductResponseVariants model = new GetMarketProductResponseVariants();

    /**
     * Model tests for GetMarketProductResponseVariants
     */
    @Test
    public void testGetMarketProductResponseVariants() {
        // TODO: test GetMarketProductResponseVariants
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'label'
     */
    @Test
    public void labelTest() {
        // TODO: test label
    }

    /**
     * Test the property 'sortKey'
     */
    @Test
    public void sortKeyTest() {
        // TODO: test sortKey
    }

    /**
     * Test the property 'externalId'
     */
    @Test
    public void externalIdTest() {
        // TODO: test externalId
    }

    /**
     * Test the property 'externalSource'
     */
    @Test
    public void externalSourceTest() {
        // TODO: test externalSource
    }

    /**
     * Test the property 'externalSyncedAt'
     */
    @Test
    public void externalSyncedAtTest() {
        // TODO: test externalSyncedAt
    }

    /**
     * Test the property 'lastSaleCents'
     */
    @Test
    public void lastSaleCentsTest() {
        // TODO: test lastSaleCents
    }

    /**
     * Test the property 'tradesCount'
     */
    @Test
    public void tradesCountTest() {
        // TODO: test tradesCount
    }

    /**
     * Test the property 'skuId'
     */
    @Test
    public void skuIdTest() {
        // TODO: test skuId
    }

    /**
     * Test the property 'lastSaleAt'
     */
    @Test
    public void lastSaleAtTest() {
        // TODO: test lastSaleAt
    }

    /**
     * Test the property 'bestBidCents'
     */
    @Test
    public void bestBidCentsTest() {
        // TODO: test bestBidCents
    }

    /**
     * Test the property 'bestAskCents'
     */
    @Test
    public void bestAskCentsTest() {
        // TODO: test bestAskCents
    }

}
