/*
 * Crossly Seller API
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.GetTaxonomyRequiredFieldResponseRequiredFields;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for GetTaxonomyRequiredFieldResponse
 */
public class GetTaxonomyRequiredFieldResponseTest {
    private final GetTaxonomyRequiredFieldResponse model = new GetTaxonomyRequiredFieldResponse();

    /**
     * Model tests for GetTaxonomyRequiredFieldResponse
     */
    @Test
    public void testGetTaxonomyRequiredFieldResponse() {
        // TODO: test GetTaxonomyRequiredFieldResponse
    }

    /**
     * Test the property 'platform'
     */
    @Test
    public void platformTest() {
        // TODO: test platform
    }

    /**
     * Test the property 'requiredFields'
     */
    @Test
    public void requiredFieldsTest() {
        // TODO: test requiredFields
    }

}
