/*
 * Crossly Seller API
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ListCbxDisbursementRulesItem
 */
public class ListCbxDisbursementRulesItemTest {
    private final ListCbxDisbursementRulesItem model = new ListCbxDisbursementRulesItem();

    /**
     * Model tests for ListCbxDisbursementRulesItem
     */
    @Test
    public void testListCbxDisbursementRulesItem() {
        // TODO: test ListCbxDisbursementRulesItem
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'thresholdBaseUnits'
     */
    @Test
    public void thresholdBaseUnitsTest() {
        // TODO: test thresholdBaseUnits
    }

    /**
     * Test the property 'distributeBps'
     */
    @Test
    public void distributeBpsTest() {
        // TODO: test distributeBps
    }

    /**
     * Test the property 'checkCadenceHours'
     */
    @Test
    public void checkCadenceHoursTest() {
        // TODO: test checkCadenceHours
    }

    /**
     * Test the property 'requireCoverageBps'
     */
    @Test
    public void requireCoverageBpsTest() {
        // TODO: test requireCoverageBps
    }

    /**
     * Test the property 'metric'
     */
    @Test
    public void metricTest() {
        // TODO: test metric
    }

    /**
     * Test the property 'lookbackDays'
     */
    @Test
    public void lookbackDaysTest() {
        // TODO: test lookbackDays
    }

    /**
     * Test the property 'maxRecipients'
     */
    @Test
    public void maxRecipientsTest() {
        // TODO: test maxRecipients
    }

    /**
     * Test the property 'isActive'
     */
    @Test
    public void isActiveTest() {
        // TODO: test isActive
    }

    /**
     * Test the property 'lastFiredAt'
     */
    @Test
    public void lastFiredAtTest() {
        // TODO: test lastFiredAt
    }

}
