/*
 * Crossly Seller API
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.ListSalesItemDocuments;
import org.openapitools.jackson.nullable.JsonNullable;
import org.threeten.bp.OffsetDateTime;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ListSalesItem
 */
public class ListSalesItemTest {
    private final ListSalesItem model = new ListSalesItem();

    /**
     * Model tests for ListSalesItem
     */
    @Test
    public void testListSalesItem() {
        // TODO: test ListSalesItem
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'userId'
     */
    @Test
    public void userIdTest() {
        // TODO: test userId
    }

    /**
     * Test the property 'platform'
     */
    @Test
    public void platformTest() {
        // TODO: test platform
    }

    /**
     * Test the property 'cancelledAt'
     */
    @Test
    public void cancelledAtTest() {
        // TODO: test cancelledAt
    }

    /**
     * Test the property 'orderId'
     */
    @Test
    public void orderIdTest() {
        // TODO: test orderId
    }

    /**
     * Test the property 'listingId'
     */
    @Test
    public void listingIdTest() {
        // TODO: test listingId
    }

    /**
     * Test the property 'inventoryItemId'
     */
    @Test
    public void inventoryItemIdTest() {
        // TODO: test inventoryItemId
    }

    /**
     * Test the property 'platformListingId'
     */
    @Test
    public void platformListingIdTest() {
        // TODO: test platformListingId
    }

    /**
     * Test the property 'platformOrderId'
     */
    @Test
    public void platformOrderIdTest() {
        // TODO: test platformOrderId
    }

    /**
     * Test the property 'costOfGoods'
     */
    @Test
    public void costOfGoodsTest() {
        // TODO: test costOfGoods
    }

    /**
     * Test the property 'deletedAt'
     */
    @Test
    public void deletedAtTest() {
        // TODO: test deletedAt
    }

    /**
     * Test the property 'salePrice'
     */
    @Test
    public void salePriceTest() {
        // TODO: test salePrice
    }

    /**
     * Test the property 'platformFee'
     */
    @Test
    public void platformFeeTest() {
        // TODO: test platformFee
    }

    /**
     * Test the property 'shippingCost'
     */
    @Test
    public void shippingCostTest() {
        // TODO: test shippingCost
    }

    /**
     * Test the property 'netProfit'
     */
    @Test
    public void netProfitTest() {
        // TODO: test netProfit
    }

    /**
     * Test the property 'taxCollected'
     */
    @Test
    public void taxCollectedTest() {
        // TODO: test taxCollected
    }

    /**
     * Test the property 'shippingCharged'
     */
    @Test
    public void shippingChargedTest() {
        // TODO: test shippingCharged
    }

    /**
     * Test the property 'feeSource'
     */
    @Test
    public void feeSourceTest() {
        // TODO: test feeSource
    }

    /**
     * Test the property 'detectedBy'
     */
    @Test
    public void detectedByTest() {
        // TODO: test detectedBy
    }

    /**
     * Test the property 'detectedAt'
     */
    @Test
    public void detectedAtTest() {
        // TODO: test detectedAt
    }

    /**
     * Test the property 'documents'
     */
    @Test
    public void documentsTest() {
        // TODO: test documents
    }

    /**
     * Test the property 'refundedAmount'
     */
    @Test
    public void refundedAmountTest() {
        // TODO: test refundedAmount
    }

}
