/*
 * Crossly Seller API
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;

/**
 * CreateCbxAccrualResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-09-17T03:09:27.794-04:00[America/New_York]")
public class CreateCbxAccrualResponse {
  public static final String SERIALIZED_NAME_DUPLICATE = "duplicate";
  @SerializedName(SERIALIZED_NAME_DUPLICATE)
  private Boolean duplicate;

  public static final String SERIALIZED_NAME_SOURCE_EXTERNAL_ID = "sourceExternalId";
  @SerializedName(SERIALIZED_NAME_SOURCE_EXTERNAL_ID)
  private String sourceExternalId;

  public CreateCbxAccrualResponse() { 
  }

  public CreateCbxAccrualResponse duplicate(Boolean duplicate) {
    
    this.duplicate = duplicate;
    return this;
  }

   /**
   * Get duplicate
   * @return duplicate
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Boolean getDuplicate() {
    return duplicate;
  }


  public void setDuplicate(Boolean duplicate) {
    this.duplicate = duplicate;
  }


  public CreateCbxAccrualResponse sourceExternalId(String sourceExternalId) {
    
    this.sourceExternalId = sourceExternalId;
    return this;
  }

   /**
   * Get sourceExternalId
   * @return sourceExternalId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getSourceExternalId() {
    return sourceExternalId;
  }


  public void setSourceExternalId(String sourceExternalId) {
    this.sourceExternalId = sourceExternalId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateCbxAccrualResponse createCbxAccrualResponse = (CreateCbxAccrualResponse) o;
    return Objects.equals(this.duplicate, createCbxAccrualResponse.duplicate) &&
        Objects.equals(this.sourceExternalId, createCbxAccrualResponse.sourceExternalId);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(duplicate, sourceExternalId);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateCbxAccrualResponse {\n");
    sb.append("    duplicate: ").append(toIndentedString(duplicate)).append("\n");
    sb.append("    sourceExternalId: ").append(toIndentedString(sourceExternalId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

