/*
 * Crossly Seller API
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;

/**
 * CreateCbxRedemptionResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-09-17T03:09:27.794-04:00[America/New_York]")
public class CreateCbxRedemptionResponse {
  public static final String SERIALIZED_NAME_REDEMPTION_ID = "redemptionId";
  @SerializedName(SERIALIZED_NAME_REDEMPTION_ID)
  private String redemptionId;

  public static final String SERIALIZED_NAME_DUPLICATE = "duplicate";
  @SerializedName(SERIALIZED_NAME_DUPLICATE)
  private Boolean duplicate;

  public static final String SERIALIZED_NAME_BASE_UNITS = "baseUnits";
  @SerializedName(SERIALIZED_NAME_BASE_UNITS)
  private String baseUnits;

  public static final String SERIALIZED_NAME_CHARGED_CENTS = "chargedCents";
  @SerializedName(SERIALIZED_NAME_CHARGED_CENTS)
  private BigDecimal chargedCents;

  public static final String SERIALIZED_NAME_DISCOUNT_BPS = "discountBps";
  @SerializedName(SERIALIZED_NAME_DISCOUNT_BPS)
  private BigDecimal discountBps;

  public CreateCbxRedemptionResponse() { 
  }

  public CreateCbxRedemptionResponse redemptionId(String redemptionId) {
    
    this.redemptionId = redemptionId;
    return this;
  }

   /**
   * Get redemptionId
   * @return redemptionId
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getRedemptionId() {
    return redemptionId;
  }


  public void setRedemptionId(String redemptionId) {
    this.redemptionId = redemptionId;
  }


  public CreateCbxRedemptionResponse duplicate(Boolean duplicate) {
    
    this.duplicate = duplicate;
    return this;
  }

   /**
   * Get duplicate
   * @return duplicate
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Boolean getDuplicate() {
    return duplicate;
  }


  public void setDuplicate(Boolean duplicate) {
    this.duplicate = duplicate;
  }


  public CreateCbxRedemptionResponse baseUnits(String baseUnits) {
    
    this.baseUnits = baseUnits;
    return this;
  }

   /**
   * Get baseUnits
   * @return baseUnits
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getBaseUnits() {
    return baseUnits;
  }


  public void setBaseUnits(String baseUnits) {
    this.baseUnits = baseUnits;
  }


  public CreateCbxRedemptionResponse chargedCents(BigDecimal chargedCents) {
    
    this.chargedCents = chargedCents;
    return this;
  }

   /**
   * Get chargedCents
   * @return chargedCents
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public BigDecimal getChargedCents() {
    return chargedCents;
  }


  public void setChargedCents(BigDecimal chargedCents) {
    this.chargedCents = chargedCents;
  }


  public CreateCbxRedemptionResponse discountBps(BigDecimal discountBps) {
    
    this.discountBps = discountBps;
    return this;
  }

   /**
   * Get discountBps
   * @return discountBps
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public BigDecimal getDiscountBps() {
    return discountBps;
  }


  public void setDiscountBps(BigDecimal discountBps) {
    this.discountBps = discountBps;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateCbxRedemptionResponse createCbxRedemptionResponse = (CreateCbxRedemptionResponse) o;
    return Objects.equals(this.redemptionId, createCbxRedemptionResponse.redemptionId) &&
        Objects.equals(this.duplicate, createCbxRedemptionResponse.duplicate) &&
        Objects.equals(this.baseUnits, createCbxRedemptionResponse.baseUnits) &&
        Objects.equals(this.chargedCents, createCbxRedemptionResponse.chargedCents) &&
        Objects.equals(this.discountBps, createCbxRedemptionResponse.discountBps);
  }

  @Override
  public int hashCode() {
    return Objects.hash(redemptionId, duplicate, baseUnits, chargedCents, discountBps);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateCbxRedemptionResponse {\n");
    sb.append("    redemptionId: ").append(toIndentedString(redemptionId)).append("\n");
    sb.append("    duplicate: ").append(toIndentedString(duplicate)).append("\n");
    sb.append("    baseUnits: ").append(toIndentedString(baseUnits)).append("\n");
    sb.append("    chargedCents: ").append(toIndentedString(chargedCents)).append("\n");
    sb.append("    discountBps: ").append(toIndentedString(discountBps)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

