/*
 * Crossly Seller API
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import org.openapitools.jackson.nullable.JsonNullable;
import org.threeten.bp.OffsetDateTime;

/**
 * GetAnalyticDashboardResponseTop5ItemsByRevenue
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-09-17T03:09:27.794-04:00[America/New_York]")
public class GetAnalyticDashboardResponseTop5ItemsByRevenue {
  public static final String SERIALIZED_NAME_SALE_ID = "saleId";
  @SerializedName(SERIALIZED_NAME_SALE_ID)
  private String saleId;

  public static final String SERIALIZED_NAME_PLATFORM = "platform";
  @SerializedName(SERIALIZED_NAME_PLATFORM)
  private String platform;

  public static final String SERIALIZED_NAME_SALE_PRICE = "salePrice";
  @SerializedName(SERIALIZED_NAME_SALE_PRICE)
  private BigDecimal salePrice;

  public static final String SERIALIZED_NAME_NET_PROFIT = "netProfit";
  @SerializedName(SERIALIZED_NAME_NET_PROFIT)
  private BigDecimal netProfit;

  public static final String SERIALIZED_NAME_DETECTED_AT = "detectedAt";
  @SerializedName(SERIALIZED_NAME_DETECTED_AT)
  private OffsetDateTime detectedAt;

  public static final String SERIALIZED_NAME_ITEM_TITLE = "itemTitle";
  @SerializedName(SERIALIZED_NAME_ITEM_TITLE)
  private String itemTitle;

  public static final String SERIALIZED_NAME_ITEM_IMAGE = "itemImage";
  @SerializedName(SERIALIZED_NAME_ITEM_IMAGE)
  private String itemImage;

  public GetAnalyticDashboardResponseTop5ItemsByRevenue() { 
  }

  public GetAnalyticDashboardResponseTop5ItemsByRevenue saleId(String saleId) {
    
    this.saleId = saleId;
    return this;
  }

   /**
   * Get saleId
   * @return saleId
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getSaleId() {
    return saleId;
  }


  public void setSaleId(String saleId) {
    this.saleId = saleId;
  }


  public GetAnalyticDashboardResponseTop5ItemsByRevenue platform(String platform) {
    
    this.platform = platform;
    return this;
  }

   /**
   * Get platform
   * @return platform
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getPlatform() {
    return platform;
  }


  public void setPlatform(String platform) {
    this.platform = platform;
  }


  public GetAnalyticDashboardResponseTop5ItemsByRevenue salePrice(BigDecimal salePrice) {
    
    this.salePrice = salePrice;
    return this;
  }

   /**
   * Get salePrice
   * @return salePrice
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BigDecimal getSalePrice() {
    return salePrice;
  }


  public void setSalePrice(BigDecimal salePrice) {
    this.salePrice = salePrice;
  }


  public GetAnalyticDashboardResponseTop5ItemsByRevenue netProfit(BigDecimal netProfit) {
    
    this.netProfit = netProfit;
    return this;
  }

   /**
   * Get netProfit
   * @return netProfit
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BigDecimal getNetProfit() {
    return netProfit;
  }


  public void setNetProfit(BigDecimal netProfit) {
    this.netProfit = netProfit;
  }


  public GetAnalyticDashboardResponseTop5ItemsByRevenue detectedAt(OffsetDateTime detectedAt) {
    
    this.detectedAt = detectedAt;
    return this;
  }

   /**
   * Get detectedAt
   * @return detectedAt
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public OffsetDateTime getDetectedAt() {
    return detectedAt;
  }


  public void setDetectedAt(OffsetDateTime detectedAt) {
    this.detectedAt = detectedAt;
  }


  public GetAnalyticDashboardResponseTop5ItemsByRevenue itemTitle(String itemTitle) {
    
    this.itemTitle = itemTitle;
    return this;
  }

   /**
   * Get itemTitle
   * @return itemTitle
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getItemTitle() {
    return itemTitle;
  }


  public void setItemTitle(String itemTitle) {
    this.itemTitle = itemTitle;
  }


  public GetAnalyticDashboardResponseTop5ItemsByRevenue itemImage(String itemImage) {
    
    this.itemImage = itemImage;
    return this;
  }

   /**
   * Get itemImage
   * @return itemImage
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getItemImage() {
    return itemImage;
  }


  public void setItemImage(String itemImage) {
    this.itemImage = itemImage;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetAnalyticDashboardResponseTop5ItemsByRevenue getAnalyticDashboardResponseTop5ItemsByRevenue = (GetAnalyticDashboardResponseTop5ItemsByRevenue) o;
    return Objects.equals(this.saleId, getAnalyticDashboardResponseTop5ItemsByRevenue.saleId) &&
        Objects.equals(this.platform, getAnalyticDashboardResponseTop5ItemsByRevenue.platform) &&
        Objects.equals(this.salePrice, getAnalyticDashboardResponseTop5ItemsByRevenue.salePrice) &&
        Objects.equals(this.netProfit, getAnalyticDashboardResponseTop5ItemsByRevenue.netProfit) &&
        Objects.equals(this.detectedAt, getAnalyticDashboardResponseTop5ItemsByRevenue.detectedAt) &&
        Objects.equals(this.itemTitle, getAnalyticDashboardResponseTop5ItemsByRevenue.itemTitle) &&
        Objects.equals(this.itemImage, getAnalyticDashboardResponseTop5ItemsByRevenue.itemImage);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(saleId, platform, salePrice, netProfit, detectedAt, itemTitle, itemImage);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetAnalyticDashboardResponseTop5ItemsByRevenue {\n");
    sb.append("    saleId: ").append(toIndentedString(saleId)).append("\n");
    sb.append("    platform: ").append(toIndentedString(platform)).append("\n");
    sb.append("    salePrice: ").append(toIndentedString(salePrice)).append("\n");
    sb.append("    netProfit: ").append(toIndentedString(netProfit)).append("\n");
    sb.append("    detectedAt: ").append(toIndentedString(detectedAt)).append("\n");
    sb.append("    itemTitle: ").append(toIndentedString(itemTitle)).append("\n");
    sb.append("    itemImage: ").append(toIndentedString(itemImage)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

