/*
 * Crossly Seller API
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;

/**
 * GetCbxMeResponseTerms
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-09-17T03:09:27.794-04:00[America/New_York]")
public class GetCbxMeResponseTerms {
  public static final String SERIALIZED_NAME_EARN_RATE_BPS = "earnRateBps";
  @SerializedName(SERIALIZED_NAME_EARN_RATE_BPS)
  private BigDecimal earnRateBps;

  public static final String SERIALIZED_NAME_PURCHASE_MATURATION_DAYS = "purchaseMaturationDays";
  @SerializedName(SERIALIZED_NAME_PURCHASE_MATURATION_DAYS)
  private BigDecimal purchaseMaturationDays;

  public static final String SERIALIZED_NAME_CLAIM_MIN_CENTS = "claimMinCents";
  @SerializedName(SERIALIZED_NAME_CLAIM_MIN_CENTS)
  private BigDecimal claimMinCents;

  public static final String SERIALIZED_NAME_WITHDRAWAL_FEE_BPS = "withdrawalFeeBps";
  @SerializedName(SERIALIZED_NAME_WITHDRAWAL_FEE_BPS)
  private BigDecimal withdrawalFeeBps;

  public static final String SERIALIZED_NAME_WITHDRAWAL_FEE_MIN_CENTS = "withdrawalFeeMinCents";
  @SerializedName(SERIALIZED_NAME_WITHDRAWAL_FEE_MIN_CENTS)
  private BigDecimal withdrawalFeeMinCents;

  public static final String SERIALIZED_NAME_WITHDRAWAL_FEE_MAX_CENTS = "withdrawalFeeMaxCents";
  @SerializedName(SERIALIZED_NAME_WITHDRAWAL_FEE_MAX_CENTS)
  private BigDecimal withdrawalFeeMaxCents;

  public static final String SERIALIZED_NAME_INACTIVITY_EXPIRY_DAYS = "inactivityExpiryDays";
  @SerializedName(SERIALIZED_NAME_INACTIVITY_EXPIRY_DAYS)
  private BigDecimal inactivityExpiryDays;

  public static final String SERIALIZED_NAME_CLAIMS_ENABLED = "claimsEnabled";
  @SerializedName(SERIALIZED_NAME_CLAIMS_ENABLED)
  private Boolean claimsEnabled;

  public GetCbxMeResponseTerms() { 
  }

  public GetCbxMeResponseTerms earnRateBps(BigDecimal earnRateBps) {
    
    this.earnRateBps = earnRateBps;
    return this;
  }

   /**
   * Get earnRateBps
   * @return earnRateBps
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public BigDecimal getEarnRateBps() {
    return earnRateBps;
  }


  public void setEarnRateBps(BigDecimal earnRateBps) {
    this.earnRateBps = earnRateBps;
  }


  public GetCbxMeResponseTerms purchaseMaturationDays(BigDecimal purchaseMaturationDays) {
    
    this.purchaseMaturationDays = purchaseMaturationDays;
    return this;
  }

   /**
   * Get purchaseMaturationDays
   * @return purchaseMaturationDays
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public BigDecimal getPurchaseMaturationDays() {
    return purchaseMaturationDays;
  }


  public void setPurchaseMaturationDays(BigDecimal purchaseMaturationDays) {
    this.purchaseMaturationDays = purchaseMaturationDays;
  }


  public GetCbxMeResponseTerms claimMinCents(BigDecimal claimMinCents) {
    
    this.claimMinCents = claimMinCents;
    return this;
  }

   /**
   * Get claimMinCents
   * @return claimMinCents
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public BigDecimal getClaimMinCents() {
    return claimMinCents;
  }


  public void setClaimMinCents(BigDecimal claimMinCents) {
    this.claimMinCents = claimMinCents;
  }


  public GetCbxMeResponseTerms withdrawalFeeBps(BigDecimal withdrawalFeeBps) {
    
    this.withdrawalFeeBps = withdrawalFeeBps;
    return this;
  }

   /**
   * Get withdrawalFeeBps
   * @return withdrawalFeeBps
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public BigDecimal getWithdrawalFeeBps() {
    return withdrawalFeeBps;
  }


  public void setWithdrawalFeeBps(BigDecimal withdrawalFeeBps) {
    this.withdrawalFeeBps = withdrawalFeeBps;
  }


  public GetCbxMeResponseTerms withdrawalFeeMinCents(BigDecimal withdrawalFeeMinCents) {
    
    this.withdrawalFeeMinCents = withdrawalFeeMinCents;
    return this;
  }

   /**
   * Get withdrawalFeeMinCents
   * @return withdrawalFeeMinCents
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public BigDecimal getWithdrawalFeeMinCents() {
    return withdrawalFeeMinCents;
  }


  public void setWithdrawalFeeMinCents(BigDecimal withdrawalFeeMinCents) {
    this.withdrawalFeeMinCents = withdrawalFeeMinCents;
  }


  public GetCbxMeResponseTerms withdrawalFeeMaxCents(BigDecimal withdrawalFeeMaxCents) {
    
    this.withdrawalFeeMaxCents = withdrawalFeeMaxCents;
    return this;
  }

   /**
   * Get withdrawalFeeMaxCents
   * @return withdrawalFeeMaxCents
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public BigDecimal getWithdrawalFeeMaxCents() {
    return withdrawalFeeMaxCents;
  }


  public void setWithdrawalFeeMaxCents(BigDecimal withdrawalFeeMaxCents) {
    this.withdrawalFeeMaxCents = withdrawalFeeMaxCents;
  }


  public GetCbxMeResponseTerms inactivityExpiryDays(BigDecimal inactivityExpiryDays) {
    
    this.inactivityExpiryDays = inactivityExpiryDays;
    return this;
  }

   /**
   * Get inactivityExpiryDays
   * @return inactivityExpiryDays
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public BigDecimal getInactivityExpiryDays() {
    return inactivityExpiryDays;
  }


  public void setInactivityExpiryDays(BigDecimal inactivityExpiryDays) {
    this.inactivityExpiryDays = inactivityExpiryDays;
  }


  public GetCbxMeResponseTerms claimsEnabled(Boolean claimsEnabled) {
    
    this.claimsEnabled = claimsEnabled;
    return this;
  }

   /**
   * Get claimsEnabled
   * @return claimsEnabled
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Boolean getClaimsEnabled() {
    return claimsEnabled;
  }


  public void setClaimsEnabled(Boolean claimsEnabled) {
    this.claimsEnabled = claimsEnabled;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetCbxMeResponseTerms getCbxMeResponseTerms = (GetCbxMeResponseTerms) o;
    return Objects.equals(this.earnRateBps, getCbxMeResponseTerms.earnRateBps) &&
        Objects.equals(this.purchaseMaturationDays, getCbxMeResponseTerms.purchaseMaturationDays) &&
        Objects.equals(this.claimMinCents, getCbxMeResponseTerms.claimMinCents) &&
        Objects.equals(this.withdrawalFeeBps, getCbxMeResponseTerms.withdrawalFeeBps) &&
        Objects.equals(this.withdrawalFeeMinCents, getCbxMeResponseTerms.withdrawalFeeMinCents) &&
        Objects.equals(this.withdrawalFeeMaxCents, getCbxMeResponseTerms.withdrawalFeeMaxCents) &&
        Objects.equals(this.inactivityExpiryDays, getCbxMeResponseTerms.inactivityExpiryDays) &&
        Objects.equals(this.claimsEnabled, getCbxMeResponseTerms.claimsEnabled);
  }

  @Override
  public int hashCode() {
    return Objects.hash(earnRateBps, purchaseMaturationDays, claimMinCents, withdrawalFeeBps, withdrawalFeeMinCents, withdrawalFeeMaxCents, inactivityExpiryDays, claimsEnabled);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetCbxMeResponseTerms {\n");
    sb.append("    earnRateBps: ").append(toIndentedString(earnRateBps)).append("\n");
    sb.append("    purchaseMaturationDays: ").append(toIndentedString(purchaseMaturationDays)).append("\n");
    sb.append("    claimMinCents: ").append(toIndentedString(claimMinCents)).append("\n");
    sb.append("    withdrawalFeeBps: ").append(toIndentedString(withdrawalFeeBps)).append("\n");
    sb.append("    withdrawalFeeMinCents: ").append(toIndentedString(withdrawalFeeMinCents)).append("\n");
    sb.append("    withdrawalFeeMaxCents: ").append(toIndentedString(withdrawalFeeMaxCents)).append("\n");
    sb.append("    inactivityExpiryDays: ").append(toIndentedString(inactivityExpiryDays)).append("\n");
    sb.append("    claimsEnabled: ").append(toIndentedString(claimsEnabled)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

