/*
 * Crossly Seller API
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.threeten.bp.OffsetDateTime;

/**
 * GetMagicDraftResponseDraft
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-09-17T03:09:27.794-04:00[America/New_York]")
public class GetMagicDraftResponseDraft {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_CREATED_AT = "createdAt";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  private OffsetDateTime createdAt;

  public static final String SERIALIZED_NAME_USER_ID = "userId";
  @SerializedName(SERIALIZED_NAME_USER_ID)
  private String userId;

  public static final String SERIALIZED_NAME_LISTING_ID = "listingId";
  @SerializedName(SERIALIZED_NAME_LISTING_ID)
  private String listingId;

  public static final String SERIALIZED_NAME_RUN_ID = "runId";
  @SerializedName(SERIALIZED_NAME_RUN_ID)
  private String runId;

  public static final String SERIALIZED_NAME_SELECTED_MATCH_KEYS = "selectedMatchKeys";
  @SerializedName(SERIALIZED_NAME_SELECTED_MATCH_KEYS)
  private List<String> selectedMatchKeys = null;

  public static final String SERIALIZED_NAME_CHOSEN_PRICE_CENTS = "chosenPriceCents";
  @SerializedName(SERIALIZED_NAME_CHOSEN_PRICE_CENTS)
  private BigDecimal chosenPriceCents;

  public static final String SERIALIZED_NAME_CHOSEN_QUANTITY = "chosenQuantity";
  @SerializedName(SERIALIZED_NAME_CHOSEN_QUANTITY)
  private BigDecimal chosenQuantity;

  public static final String SERIALIZED_NAME_CHOSEN_CONDITION = "chosenCondition";
  @SerializedName(SERIALIZED_NAME_CHOSEN_CONDITION)
  private String chosenCondition;

  public GetMagicDraftResponseDraft() { 
  }

  public GetMagicDraftResponseDraft id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getId() {
    return id;
  }


  public void setId(String id) {
    this.id = id;
  }


  public GetMagicDraftResponseDraft createdAt(OffsetDateTime createdAt) {
    
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }


  public void setCreatedAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public GetMagicDraftResponseDraft userId(String userId) {
    
    this.userId = userId;
    return this;
  }

   /**
   * Get userId
   * @return userId
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getUserId() {
    return userId;
  }


  public void setUserId(String userId) {
    this.userId = userId;
  }


  public GetMagicDraftResponseDraft listingId(String listingId) {
    
    this.listingId = listingId;
    return this;
  }

   /**
   * Get listingId
   * @return listingId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getListingId() {
    return listingId;
  }


  public void setListingId(String listingId) {
    this.listingId = listingId;
  }


  public GetMagicDraftResponseDraft runId(String runId) {
    
    this.runId = runId;
    return this;
  }

   /**
   * Get runId
   * @return runId
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getRunId() {
    return runId;
  }


  public void setRunId(String runId) {
    this.runId = runId;
  }


  public GetMagicDraftResponseDraft selectedMatchKeys(List<String> selectedMatchKeys) {
    
    this.selectedMatchKeys = selectedMatchKeys;
    return this;
  }

  public GetMagicDraftResponseDraft addSelectedMatchKeysItem(String selectedMatchKeysItem) {
    if (this.selectedMatchKeys == null) {
      this.selectedMatchKeys = new ArrayList<String>();
    }
    this.selectedMatchKeys.add(selectedMatchKeysItem);
    return this;
  }

   /**
   * Get selectedMatchKeys
   * @return selectedMatchKeys
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<String> getSelectedMatchKeys() {
    return selectedMatchKeys;
  }


  public void setSelectedMatchKeys(List<String> selectedMatchKeys) {
    this.selectedMatchKeys = selectedMatchKeys;
  }


  public GetMagicDraftResponseDraft chosenPriceCents(BigDecimal chosenPriceCents) {
    
    this.chosenPriceCents = chosenPriceCents;
    return this;
  }

   /**
   * Get chosenPriceCents
   * @return chosenPriceCents
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BigDecimal getChosenPriceCents() {
    return chosenPriceCents;
  }


  public void setChosenPriceCents(BigDecimal chosenPriceCents) {
    this.chosenPriceCents = chosenPriceCents;
  }


  public GetMagicDraftResponseDraft chosenQuantity(BigDecimal chosenQuantity) {
    
    this.chosenQuantity = chosenQuantity;
    return this;
  }

   /**
   * Get chosenQuantity
   * @return chosenQuantity
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BigDecimal getChosenQuantity() {
    return chosenQuantity;
  }


  public void setChosenQuantity(BigDecimal chosenQuantity) {
    this.chosenQuantity = chosenQuantity;
  }


  public GetMagicDraftResponseDraft chosenCondition(String chosenCondition) {
    
    this.chosenCondition = chosenCondition;
    return this;
  }

   /**
   * Get chosenCondition
   * @return chosenCondition
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getChosenCondition() {
    return chosenCondition;
  }


  public void setChosenCondition(String chosenCondition) {
    this.chosenCondition = chosenCondition;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetMagicDraftResponseDraft getMagicDraftResponseDraft = (GetMagicDraftResponseDraft) o;
    return Objects.equals(this.id, getMagicDraftResponseDraft.id) &&
        Objects.equals(this.createdAt, getMagicDraftResponseDraft.createdAt) &&
        Objects.equals(this.userId, getMagicDraftResponseDraft.userId) &&
        Objects.equals(this.listingId, getMagicDraftResponseDraft.listingId) &&
        Objects.equals(this.runId, getMagicDraftResponseDraft.runId) &&
        Objects.equals(this.selectedMatchKeys, getMagicDraftResponseDraft.selectedMatchKeys) &&
        Objects.equals(this.chosenPriceCents, getMagicDraftResponseDraft.chosenPriceCents) &&
        Objects.equals(this.chosenQuantity, getMagicDraftResponseDraft.chosenQuantity) &&
        Objects.equals(this.chosenCondition, getMagicDraftResponseDraft.chosenCondition);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, createdAt, userId, listingId, runId, selectedMatchKeys, chosenPriceCents, chosenQuantity, chosenCondition);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetMagicDraftResponseDraft {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    listingId: ").append(toIndentedString(listingId)).append("\n");
    sb.append("    runId: ").append(toIndentedString(runId)).append("\n");
    sb.append("    selectedMatchKeys: ").append(toIndentedString(selectedMatchKeys)).append("\n");
    sb.append("    chosenPriceCents: ").append(toIndentedString(chosenPriceCents)).append("\n");
    sb.append("    chosenQuantity: ").append(toIndentedString(chosenQuantity)).append("\n");
    sb.append("    chosenCondition: ").append(toIndentedString(chosenCondition)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

