/*
 * Crossly Seller API
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.GetVariationGroupPublishPlanResponsePlans;

/**
 * GetVariationGroupPublishPlanResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-09-17T03:09:27.794-04:00[America/New_York]")
public class GetVariationGroupPublishPlanResponse {
  public static final String SERIALIZED_NAME_PLANS = "plans";
  @SerializedName(SERIALIZED_NAME_PLANS)
  private List<GetVariationGroupPublishPlanResponsePlans> plans = new ArrayList<GetVariationGroupPublishPlanResponsePlans>();

  public static final String SERIALIZED_NAME_TOTAL_LISTINGS = "totalListings";
  @SerializedName(SERIALIZED_NAME_TOTAL_LISTINGS)
  private BigDecimal totalListings;

  public static final String SERIALIZED_NAME_MEMBER_COUNT = "memberCount";
  @SerializedName(SERIALIZED_NAME_MEMBER_COUNT)
  private BigDecimal memberCount;

  public static final String SERIALIZED_NAME_AXIS_NAME = "axisName";
  @SerializedName(SERIALIZED_NAME_AXIS_NAME)
  private String axisName;

  public GetVariationGroupPublishPlanResponse() { 
  }

  public GetVariationGroupPublishPlanResponse plans(List<GetVariationGroupPublishPlanResponsePlans> plans) {
    
    this.plans = plans;
    return this;
  }

  public GetVariationGroupPublishPlanResponse addPlansItem(GetVariationGroupPublishPlanResponsePlans plansItem) {
    this.plans.add(plansItem);
    return this;
  }

   /**
   * Get plans
   * @return plans
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public List<GetVariationGroupPublishPlanResponsePlans> getPlans() {
    return plans;
  }


  public void setPlans(List<GetVariationGroupPublishPlanResponsePlans> plans) {
    this.plans = plans;
  }


  public GetVariationGroupPublishPlanResponse totalListings(BigDecimal totalListings) {
    
    this.totalListings = totalListings;
    return this;
  }

   /**
   * Get totalListings
   * @return totalListings
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public BigDecimal getTotalListings() {
    return totalListings;
  }


  public void setTotalListings(BigDecimal totalListings) {
    this.totalListings = totalListings;
  }


  public GetVariationGroupPublishPlanResponse memberCount(BigDecimal memberCount) {
    
    this.memberCount = memberCount;
    return this;
  }

   /**
   * Get memberCount
   * @return memberCount
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public BigDecimal getMemberCount() {
    return memberCount;
  }


  public void setMemberCount(BigDecimal memberCount) {
    this.memberCount = memberCount;
  }


  public GetVariationGroupPublishPlanResponse axisName(String axisName) {
    
    this.axisName = axisName;
    return this;
  }

   /**
   * Get axisName
   * @return axisName
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getAxisName() {
    return axisName;
  }


  public void setAxisName(String axisName) {
    this.axisName = axisName;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetVariationGroupPublishPlanResponse getVariationGroupPublishPlanResponse = (GetVariationGroupPublishPlanResponse) o;
    return Objects.equals(this.plans, getVariationGroupPublishPlanResponse.plans) &&
        Objects.equals(this.totalListings, getVariationGroupPublishPlanResponse.totalListings) &&
        Objects.equals(this.memberCount, getVariationGroupPublishPlanResponse.memberCount) &&
        Objects.equals(this.axisName, getVariationGroupPublishPlanResponse.axisName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(plans, totalListings, memberCount, axisName);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetVariationGroupPublishPlanResponse {\n");
    sb.append("    plans: ").append(toIndentedString(plans)).append("\n");
    sb.append("    totalListings: ").append(toIndentedString(totalListings)).append("\n");
    sb.append("    memberCount: ").append(toIndentedString(memberCount)).append("\n");
    sb.append("    axisName: ").append(toIndentedString(axisName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

