/*
 * Crossly Seller API
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;

/**
 * ListBuyerCatalogSearchItem
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-09-17T03:09:27.794-04:00[America/New_York]")
public class ListBuyerCatalogSearchItem {
  public static final String SERIALIZED_NAME_SLUG = "slug";
  @SerializedName(SERIALIZED_NAME_SLUG)
  private String slug;

  public static final String SERIALIZED_NAME_TITLE = "title";
  @SerializedName(SERIALIZED_NAME_TITLE)
  private String title;

  public static final String SERIALIZED_NAME_PRICE_CENTS = "priceCents";
  @SerializedName(SERIALIZED_NAME_PRICE_CENTS)
  private BigDecimal priceCents;

  public static final String SERIALIZED_NAME_COMPARE_AT_CENTS = "compareAtCents";
  @SerializedName(SERIALIZED_NAME_COMPARE_AT_CENTS)
  private BigDecimal compareAtCents;

  public static final String SERIALIZED_NAME_CURRENCY = "currency";
  @SerializedName(SERIALIZED_NAME_CURRENCY)
  private String currency;

  public static final String SERIALIZED_NAME_CONDITION = "condition";
  @SerializedName(SERIALIZED_NAME_CONDITION)
  private String condition;

  public static final String SERIALIZED_NAME_BRAND = "brand";
  @SerializedName(SERIALIZED_NAME_BRAND)
  private String brand;

  public static final String SERIALIZED_NAME_CATEGORY_MAIN = "categoryMain";
  @SerializedName(SERIALIZED_NAME_CATEGORY_MAIN)
  private String categoryMain;

  public static final String SERIALIZED_NAME_CATEGORY_SUB = "categorySub";
  @SerializedName(SERIALIZED_NAME_CATEGORY_SUB)
  private String categorySub;

  public static final String SERIALIZED_NAME_THUMBNAIL = "thumbnail";
  @SerializedName(SERIALIZED_NAME_THUMBNAIL)
  private String thumbnail;

  public static final String SERIALIZED_NAME_IMAGES = "images";
  @SerializedName(SERIALIZED_NAME_IMAGES)
  private List<String> images = new ArrayList<String>();

  public static final String SERIALIZED_NAME_SELLER_USERNAME = "sellerUsername";
  @SerializedName(SERIALIZED_NAME_SELLER_USERNAME)
  private String sellerUsername;

  public static final String SERIALIZED_NAME_SELLER_DISPLAY_NAME = "sellerDisplayName";
  @SerializedName(SERIALIZED_NAME_SELLER_DISPLAY_NAME)
  private String sellerDisplayName;

  public static final String SERIALIZED_NAME_QUANTITY_AVAILABLE = "quantityAvailable";
  @SerializedName(SERIALIZED_NAME_QUANTITY_AVAILABLE)
  private BigDecimal quantityAvailable;

  public static final String SERIALIZED_NAME_LISTED_AT = "listedAt";
  @SerializedName(SERIALIZED_NAME_LISTED_AT)
  private String listedAt;

  public static final String SERIALIZED_NAME_URL = "url";
  @SerializedName(SERIALIZED_NAME_URL)
  private String url;

  public ListBuyerCatalogSearchItem() { 
  }

  public ListBuyerCatalogSearchItem slug(String slug) {
    
    this.slug = slug;
    return this;
  }

   /**
   * Get slug
   * @return slug
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getSlug() {
    return slug;
  }


  public void setSlug(String slug) {
    this.slug = slug;
  }


  public ListBuyerCatalogSearchItem title(String title) {
    
    this.title = title;
    return this;
  }

   /**
   * Get title
   * @return title
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getTitle() {
    return title;
  }


  public void setTitle(String title) {
    this.title = title;
  }


  public ListBuyerCatalogSearchItem priceCents(BigDecimal priceCents) {
    
    this.priceCents = priceCents;
    return this;
  }

   /**
   * Get priceCents
   * @return priceCents
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public BigDecimal getPriceCents() {
    return priceCents;
  }


  public void setPriceCents(BigDecimal priceCents) {
    this.priceCents = priceCents;
  }


  public ListBuyerCatalogSearchItem compareAtCents(BigDecimal compareAtCents) {
    
    this.compareAtCents = compareAtCents;
    return this;
  }

   /**
   * MSRP above the ask, or null. Never fabricated from a stale value.
   * @return compareAtCents
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "MSRP above the ask, or null. Never fabricated from a stale value.")

  public BigDecimal getCompareAtCents() {
    return compareAtCents;
  }


  public void setCompareAtCents(BigDecimal compareAtCents) {
    this.compareAtCents = compareAtCents;
  }


  public ListBuyerCatalogSearchItem currency(String currency) {
    
    this.currency = currency;
    return this;
  }

   /**
   * Get currency
   * @return currency
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getCurrency() {
    return currency;
  }


  public void setCurrency(String currency) {
    this.currency = currency;
  }


  public ListBuyerCatalogSearchItem condition(String condition) {
    
    this.condition = condition;
    return this;
  }

   /**
   * Get condition
   * @return condition
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getCondition() {
    return condition;
  }


  public void setCondition(String condition) {
    this.condition = condition;
  }


  public ListBuyerCatalogSearchItem brand(String brand) {
    
    this.brand = brand;
    return this;
  }

   /**
   * Get brand
   * @return brand
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getBrand() {
    return brand;
  }


  public void setBrand(String brand) {
    this.brand = brand;
  }


  public ListBuyerCatalogSearchItem categoryMain(String categoryMain) {
    
    this.categoryMain = categoryMain;
    return this;
  }

   /**
   * Get categoryMain
   * @return categoryMain
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getCategoryMain() {
    return categoryMain;
  }


  public void setCategoryMain(String categoryMain) {
    this.categoryMain = categoryMain;
  }


  public ListBuyerCatalogSearchItem categorySub(String categorySub) {
    
    this.categorySub = categorySub;
    return this;
  }

   /**
   * Get categorySub
   * @return categorySub
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getCategorySub() {
    return categorySub;
  }


  public void setCategorySub(String categorySub) {
    this.categorySub = categorySub;
  }


  public ListBuyerCatalogSearchItem thumbnail(String thumbnail) {
    
    this.thumbnail = thumbnail;
    return this;
  }

   /**
   * Get thumbnail
   * @return thumbnail
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getThumbnail() {
    return thumbnail;
  }


  public void setThumbnail(String thumbnail) {
    this.thumbnail = thumbnail;
  }


  public ListBuyerCatalogSearchItem images(List<String> images) {
    
    this.images = images;
    return this;
  }

  public ListBuyerCatalogSearchItem addImagesItem(String imagesItem) {
    this.images.add(imagesItem);
    return this;
  }

   /**
   * Get images
   * @return images
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public List<String> getImages() {
    return images;
  }


  public void setImages(List<String> images) {
    this.images = images;
  }


  public ListBuyerCatalogSearchItem sellerUsername(String sellerUsername) {
    
    this.sellerUsername = sellerUsername;
    return this;
  }

   /**
   * Get sellerUsername
   * @return sellerUsername
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getSellerUsername() {
    return sellerUsername;
  }


  public void setSellerUsername(String sellerUsername) {
    this.sellerUsername = sellerUsername;
  }


  public ListBuyerCatalogSearchItem sellerDisplayName(String sellerDisplayName) {
    
    this.sellerDisplayName = sellerDisplayName;
    return this;
  }

   /**
   * Get sellerDisplayName
   * @return sellerDisplayName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getSellerDisplayName() {
    return sellerDisplayName;
  }


  public void setSellerDisplayName(String sellerDisplayName) {
    this.sellerDisplayName = sellerDisplayName;
  }


  public ListBuyerCatalogSearchItem quantityAvailable(BigDecimal quantityAvailable) {
    
    this.quantityAvailable = quantityAvailable;
    return this;
  }

   /**
   * Units a buyer can actually take right now. Reserved units are excluded.
   * @return quantityAvailable
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "Units a buyer can actually take right now. Reserved units are excluded.")

  public BigDecimal getQuantityAvailable() {
    return quantityAvailable;
  }


  public void setQuantityAvailable(BigDecimal quantityAvailable) {
    this.quantityAvailable = quantityAvailable;
  }


  public ListBuyerCatalogSearchItem listedAt(String listedAt) {
    
    this.listedAt = listedAt;
    return this;
  }

   /**
   * Get listedAt
   * @return listedAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getListedAt() {
    return listedAt;
  }


  public void setListedAt(String listedAt) {
    this.listedAt = listedAt;
  }


  public ListBuyerCatalogSearchItem url(String url) {
    
    this.url = url;
    return this;
  }

   /**
   * Canonical buyer-facing URL, so a client never has to build one.
   * @return url
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "Canonical buyer-facing URL, so a client never has to build one.")

  public String getUrl() {
    return url;
  }


  public void setUrl(String url) {
    this.url = url;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ListBuyerCatalogSearchItem listBuyerCatalogSearchItem = (ListBuyerCatalogSearchItem) o;
    return Objects.equals(this.slug, listBuyerCatalogSearchItem.slug) &&
        Objects.equals(this.title, listBuyerCatalogSearchItem.title) &&
        Objects.equals(this.priceCents, listBuyerCatalogSearchItem.priceCents) &&
        Objects.equals(this.compareAtCents, listBuyerCatalogSearchItem.compareAtCents) &&
        Objects.equals(this.currency, listBuyerCatalogSearchItem.currency) &&
        Objects.equals(this.condition, listBuyerCatalogSearchItem.condition) &&
        Objects.equals(this.brand, listBuyerCatalogSearchItem.brand) &&
        Objects.equals(this.categoryMain, listBuyerCatalogSearchItem.categoryMain) &&
        Objects.equals(this.categorySub, listBuyerCatalogSearchItem.categorySub) &&
        Objects.equals(this.thumbnail, listBuyerCatalogSearchItem.thumbnail) &&
        Objects.equals(this.images, listBuyerCatalogSearchItem.images) &&
        Objects.equals(this.sellerUsername, listBuyerCatalogSearchItem.sellerUsername) &&
        Objects.equals(this.sellerDisplayName, listBuyerCatalogSearchItem.sellerDisplayName) &&
        Objects.equals(this.quantityAvailable, listBuyerCatalogSearchItem.quantityAvailable) &&
        Objects.equals(this.listedAt, listBuyerCatalogSearchItem.listedAt) &&
        Objects.equals(this.url, listBuyerCatalogSearchItem.url);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(slug, title, priceCents, compareAtCents, currency, condition, brand, categoryMain, categorySub, thumbnail, images, sellerUsername, sellerDisplayName, quantityAvailable, listedAt, url);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ListBuyerCatalogSearchItem {\n");
    sb.append("    slug: ").append(toIndentedString(slug)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    priceCents: ").append(toIndentedString(priceCents)).append("\n");
    sb.append("    compareAtCents: ").append(toIndentedString(compareAtCents)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    condition: ").append(toIndentedString(condition)).append("\n");
    sb.append("    brand: ").append(toIndentedString(brand)).append("\n");
    sb.append("    categoryMain: ").append(toIndentedString(categoryMain)).append("\n");
    sb.append("    categorySub: ").append(toIndentedString(categorySub)).append("\n");
    sb.append("    thumbnail: ").append(toIndentedString(thumbnail)).append("\n");
    sb.append("    images: ").append(toIndentedString(images)).append("\n");
    sb.append("    sellerUsername: ").append(toIndentedString(sellerUsername)).append("\n");
    sb.append("    sellerDisplayName: ").append(toIndentedString(sellerDisplayName)).append("\n");
    sb.append("    quantityAvailable: ").append(toIndentedString(quantityAvailable)).append("\n");
    sb.append("    listedAt: ").append(toIndentedString(listedAt)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

