/*
 * Crossly Seller API
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

/**
 * ListCustomersItem
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-09-17T03:09:27.794-04:00[America/New_York]")
public class ListCustomersItem {
  public static final String SERIALIZED_NAME_NORMALIZED_HANDLE = "normalizedHandle";
  @SerializedName(SERIALIZED_NAME_NORMALIZED_HANDLE)
  private String normalizedHandle;

  public static final String SERIALIZED_NAME_PLATFORMS = "platforms";
  @SerializedName(SERIALIZED_NAME_PLATFORMS)
  private List<String> platforms = new ArrayList<String>();

  public static final String SERIALIZED_NAME_TOTAL_ORDERS = "totalOrders";
  @SerializedName(SERIALIZED_NAME_TOTAL_ORDERS)
  private BigDecimal totalOrders;

  public static final String SERIALIZED_NAME_TOTAL_SPENT = "totalSpent";
  @SerializedName(SERIALIZED_NAME_TOTAL_SPENT)
  private BigDecimal totalSpent;

  public ListCustomersItem() { 
  }

  public ListCustomersItem normalizedHandle(String normalizedHandle) {
    
    this.normalizedHandle = normalizedHandle;
    return this;
  }

   /**
   * Get normalizedHandle
   * @return normalizedHandle
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getNormalizedHandle() {
    return normalizedHandle;
  }


  public void setNormalizedHandle(String normalizedHandle) {
    this.normalizedHandle = normalizedHandle;
  }


  public ListCustomersItem platforms(List<String> platforms) {
    
    this.platforms = platforms;
    return this;
  }

  public ListCustomersItem addPlatformsItem(String platformsItem) {
    this.platforms.add(platformsItem);
    return this;
  }

   /**
   * Get platforms
   * @return platforms
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public List<String> getPlatforms() {
    return platforms;
  }


  public void setPlatforms(List<String> platforms) {
    this.platforms = platforms;
  }


  public ListCustomersItem totalOrders(BigDecimal totalOrders) {
    
    this.totalOrders = totalOrders;
    return this;
  }

   /**
   * Get totalOrders
   * @return totalOrders
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public BigDecimal getTotalOrders() {
    return totalOrders;
  }


  public void setTotalOrders(BigDecimal totalOrders) {
    this.totalOrders = totalOrders;
  }


  public ListCustomersItem totalSpent(BigDecimal totalSpent) {
    
    this.totalSpent = totalSpent;
    return this;
  }

   /**
   * Get totalSpent
   * @return totalSpent
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public BigDecimal getTotalSpent() {
    return totalSpent;
  }


  public void setTotalSpent(BigDecimal totalSpent) {
    this.totalSpent = totalSpent;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ListCustomersItem listCustomersItem = (ListCustomersItem) o;
    return Objects.equals(this.normalizedHandle, listCustomersItem.normalizedHandle) &&
        Objects.equals(this.platforms, listCustomersItem.platforms) &&
        Objects.equals(this.totalOrders, listCustomersItem.totalOrders) &&
        Objects.equals(this.totalSpent, listCustomersItem.totalSpent);
  }

  @Override
  public int hashCode() {
    return Objects.hash(normalizedHandle, platforms, totalOrders, totalSpent);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ListCustomersItem {\n");
    sb.append("    normalizedHandle: ").append(toIndentedString(normalizedHandle)).append("\n");
    sb.append("    platforms: ").append(toIndentedString(platforms)).append("\n");
    sb.append("    totalOrders: ").append(toIndentedString(totalOrders)).append("\n");
    sb.append("    totalSpent: ").append(toIndentedString(totalSpent)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

