/*
 * Crossly Seller API
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import net.crossly.ApiException;
import org.openapitools.client.model.CreateAiCategorizeFromImageResponse;
import org.openapitools.client.model.CreateAiCategorizeResponse;
import org.openapitools.client.model.CreateAiEnhanceDescriptionResponse;
import org.openapitools.client.model.CreateAiEnhanceListingResponse;
import org.openapitools.client.model.CreateAiEnhanceTitleResponse;
import org.openapitools.client.model.CreateAiExtractReceiptResponse;
import org.openapitools.client.model.CreateAiGenerateListingResponse;
import org.openapitools.client.model.CreateAiHelpResponse;
import org.openapitools.client.model.CreateAiMagicListingResponse;
import org.openapitools.client.model.CreateAiTestKeyResponse;
import org.openapitools.client.model.DeleteAiKeyResponse;
import org.openapitools.client.model.Error;
import org.openapitools.client.model.GetAiProviderResponse;
import org.openapitools.client.model.GetAiStatusResponse;
import org.openapitools.client.model.UpdateAiKeyResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AiApi
 */
@Ignore
public class AiApiTest {

    private final AiApi api = new AiApi();

    
    /**
     * Taxonomy guess from a single image URL.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createAiCategorizeTest() throws ApiException {
                CreateAiCategorizeResponse response = api.createAiCategorize();
        // TODO: test validations
    }
    
    /**
     * Taxonomy guess from a single base64 image.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createAiCategorizeFromImageTest() throws ApiException {
                CreateAiCategorizeFromImageResponse response = api.createAiCategorizeFromImage();
        // TODO: test validations
    }
    
    /**
     * SEO-rewrite a listing description.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createAiEnhanceDescriptionTest() throws ApiException {
                CreateAiEnhanceDescriptionResponse response = api.createAiEnhanceDescription();
        // TODO: test validations
    }
    
    /**
     * Rewrite title + description + tags in one call.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createAiEnhanceListingTest() throws ApiException {
                CreateAiEnhanceListingResponse response = api.createAiEnhanceListing();
        // TODO: test validations
    }
    
    /**
     * SEO-rewrite a listing title.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createAiEnhanceTitleTest() throws ApiException {
                CreateAiEnhanceTitleResponse response = api.createAiEnhanceTitle();
        // TODO: test validations
    }
    
    /**
     * Structured data extraction from a receipt photo.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createAiExtractReceiptTest() throws ApiException {
                CreateAiExtractReceiptResponse response = api.createAiExtractReceipt();
        // TODO: test validations
    }
    
    /**
     * Generate full listing fields from up to 4 image URLs.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createAiGenerateListingTest() throws ApiException {
                CreateAiGenerateListingResponse response = api.createAiGenerateListing();
        // TODO: test validations
    }
    
    /**
     * In-app help Q&amp;A grounded in supplied docs.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createAiHelpTest() throws ApiException {
                CreateAiHelpResponse response = api.createAiHelp();
        // TODO: test validations
    }
    
    /**
     * Generate full listing fields from base64 photos.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createAiMagicListingTest() throws ApiException {
                CreateAiMagicListingResponse response = api.createAiMagicListing();
        // TODO: test validations
    }
    
    /**
     * Live-ping a candidate BYO-key.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createAiTestKeyTest() throws ApiException {
                CreateAiTestKeyResponse response = api.createAiTestKey();
        // TODO: test validations
    }
    
    /**
     * Remove the BYO-key for a provider.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteAiKeyTest() throws ApiException {
                DeleteAiKeyResponse response = api.deleteAiKey();
        // TODO: test validations
    }
    
    /**
     * Static catalog of supported AI providers.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAiProviderTest() throws ApiException {
                GetAiProviderResponse response = api.getAiProvider();
        // TODO: test validations
    }
    
    /**
     * BYO-key state for the calling user.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAiStatusTest() throws ApiException {
                GetAiStatusResponse response = api.getAiStatus();
        // TODO: test validations
    }
    
    /**
     * Save an encrypted BYO-key for an AI provider.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateAiKeyTest() throws ApiException {
                UpdateAiKeyResponse response = api.updateAiKey();
        // TODO: test validations
    }
    
}
