/*
 * Crossly Seller API
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import net.crossly.ApiException;
import org.openapitools.client.model.CreateMobilePushTestResponse;
import org.openapitools.client.model.CreateMobilePushTokenResponse;
import org.openapitools.client.model.DeleteMobilePushTokenResponse;
import org.openapitools.client.model.Error;
import org.openapitools.client.model.ListMobilePushTokensItem;
import org.openapitools.client.model.V1List;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for MobileApi
 */
@Ignore
public class MobileApiTest {

    private final MobileApi api = new MobileApi();

    
    /**
     * Fire a no-op test push to this user&#39;s devices.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createMobilePushTestTest() throws ApiException {
                CreateMobilePushTestResponse response = api.createMobilePushTest();
        // TODO: test validations
    }
    
    /**
     * Register an Expo push token for this user.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createMobilePushTokenTest() throws ApiException {
                CreateMobilePushTokenResponse response = api.createMobilePushToken();
        // TODO: test validations
    }
    
    /**
     * Clear ALL registered push tokens for this user.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteMobilePushTokenTest() throws ApiException {
                DeleteMobilePushTokenResponse response = api.deleteMobilePushToken();
        // TODO: test validations
    }
    
    /**
     * List registered Expo push tokens (masked).
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listMobilePushTokensTest() throws ApiException {
                V1List response = api.listMobilePushTokens();
        // TODO: test validations
    }
    
}
