/*
 * Crossly Seller API
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import net.crossly.ApiException;
import org.openapitools.client.model.CreateSourcingReceiptResponse;
import org.openapitools.client.model.Error;
import org.openapitools.client.model.GetSourcingReceiptResponse;
import org.openapitools.client.model.ListSourcingDemandItem;
import org.openapitools.client.model.ListSourcingDemandMineItem;
import org.openapitools.client.model.V1List;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SourcingApi
 */
@Ignore
public class SourcingApiTest {

    private final SourcingApi api = new SourcingApi();

    
    /**
     * Append a parsed receipt to the sourcing ledger.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createSourcingReceiptTest() throws ApiException {
                CreateSourcingReceiptResponse response = api.createSourcingReceipt();
        // TODO: test validations
    }
    
    /**
     * List parsed sourcing receipts in this user&#39;s ledger.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getSourcingReceiptTest() throws ApiException {
                GetSourcingReceiptResponse response = api.getSourcingReceipt();
        // TODO: test validations
    }
    
    /**
     * Items buyers looked for on other sites that Crossly did not have.
     *
     * Aggregate demand observed by the Scout extension, ranked by MISSES — the times somebody asked and we had nothing. &#x60;medianPageCents&#x60; is what the retailers were charging, which is the number to source against. Anonymous in every case; there is no per-buyer view of this.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listSourcingDemandTest() throws ApiException {
        Integer days = null;
        Integer minLooks = null;
        Integer limit = null;
                V1List response = api.listSourcingDemand(days, minLooks, limit);
        // TODO: test validations
    }
    
    /**
     * Unmet buyer demand for items you hold or have sold before.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listSourcingDemandMineTest() throws ApiException {
        Integer days = null;
        Integer minLookers = null;
        Integer limit = null;
                V1List response = api.listSourcingDemandMine(days, minLookers, limit);
        // TODO: test validations
    }
    
}
