/*
 * Crossly Buyer API
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for CreateInboxConversationBulkAiRespondResponseResults
 */
public class CreateInboxConversationBulkAiRespondResponseResultsTest {
    private final CreateInboxConversationBulkAiRespondResponseResults model = new CreateInboxConversationBulkAiRespondResponseResults();

    /**
     * Model tests for CreateInboxConversationBulkAiRespondResponseResults
     */
    @Test
    public void testCreateInboxConversationBulkAiRespondResponseResults() {
        // TODO: test CreateInboxConversationBulkAiRespondResponseResults
    }

    /**
     * Test the property 'conversationId'
     */
    @Test
    public void conversationIdTest() {
        // TODO: test conversationId
    }

    /**
     * Test the property 'ok'
     */
    @Test
    public void okTest() {
        // TODO: test ok
    }

    /**
     * Test the property 'suggestion'
     */
    @Test
    public void suggestionTest() {
        // TODO: test suggestion
    }

    /**
     * Test the property 'error'
     */
    @Test
    public void errorTest() {
        // TODO: test error
    }

}
