/*
 * Crossly Buyer API
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for CreateOrderCancelResponse
 */
public class CreateOrderCancelResponseTest {
    private final CreateOrderCancelResponse model = new CreateOrderCancelResponse();

    /**
     * Model tests for CreateOrderCancelResponse
     */
    @Test
    public void testCreateOrderCancelResponse() {
        // TODO: test CreateOrderCancelResponse
    }

    /**
     * Test the property 'orderId'
     */
    @Test
    public void orderIdTest() {
        // TODO: test orderId
    }

    /**
     * Test the property 'platform'
     */
    @Test
    public void platformTest() {
        // TODO: test platform
    }

    /**
     * Test the property 'cancelledInCrossly'
     */
    @Test
    public void cancelledInCrosslyTest() {
        // TODO: test cancelledInCrossly
    }

    /**
     * Test the property 'platformCancel'
     */
    @Test
    public void platformCancelTest() {
        // TODO: test platformCancel
    }

}
