/*
 * Crossly Buyer API
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for GetCbxSubjectBalanceResponse
 */
public class GetCbxSubjectBalanceResponseTest {
    private final GetCbxSubjectBalanceResponse model = new GetCbxSubjectBalanceResponse();

    /**
     * Model tests for GetCbxSubjectBalanceResponse
     */
    @Test
    public void testGetCbxSubjectBalanceResponse() {
        // TODO: test GetCbxSubjectBalanceResponse
    }

    /**
     * Test the property 'subjectId'
     */
    @Test
    public void subjectIdTest() {
        // TODO: test subjectId
    }

    /**
     * Test the property 'availableBaseUnits'
     */
    @Test
    public void availableBaseUnitsTest() {
        // TODO: test availableBaseUnits
    }

    /**
     * Test the property 'pendingCents'
     */
    @Test
    public void pendingCentsTest() {
        // TODO: test pendingCents
    }

}
