/*
 * Crossly Buyer API
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import org.openapitools.jackson.nullable.JsonNullable;
import org.threeten.bp.OffsetDateTime;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for GetCbxTreasuryResponse
 */
public class GetCbxTreasuryResponseTest {
    private final GetCbxTreasuryResponse model = new GetCbxTreasuryResponse();

    /**
     * Model tests for GetCbxTreasuryResponse
     */
    @Test
    public void testGetCbxTreasuryResponse() {
        // TODO: test GetCbxTreasuryResponse
    }

    /**
     * Test the property 'takenAt'
     */
    @Test
    public void takenAtTest() {
        // TODO: test takenAt
    }

    /**
     * Test the property 'coverageBps'
     */
    @Test
    public void coverageBpsTest() {
        // TODO: test coverageBps
    }

    /**
     * Test the property 'ok'
     */
    @Test
    public void okTest() {
        // TODO: test ok
    }

    /**
     * Test the property 'reserveBaseUnits'
     */
    @Test
    public void reserveBaseUnitsTest() {
        // TODO: test reserveBaseUnits
    }

    /**
     * Test the property 'outstandingBaseUnits'
     */
    @Test
    public void outstandingBaseUnitsTest() {
        // TODO: test outstandingBaseUnits
    }

    /**
     * Test the property 'inFlightClaimBaseUnits'
     */
    @Test
    public void inFlightClaimBaseUnitsTest() {
        // TODO: test inFlightClaimBaseUnits
    }

    /**
     * Test the property 'notes'
     */
    @Test
    public void notesTest() {
        // TODO: test notes
    }

}
