/*
 * Crossly Buyer API
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.GetMarketVariantBookResponseBids;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for GetMarketVariantBookResponse
 */
public class GetMarketVariantBookResponseTest {
    private final GetMarketVariantBookResponse model = new GetMarketVariantBookResponse();

    /**
     * Model tests for GetMarketVariantBookResponse
     */
    @Test
    public void testGetMarketVariantBookResponse() {
        // TODO: test GetMarketVariantBookResponse
    }

    /**
     * Test the property 'condition'
     */
    @Test
    public void conditionTest() {
        // TODO: test condition
    }

    /**
     * Test the property 'gradeKey'
     */
    @Test
    public void gradeKeyTest() {
        // TODO: test gradeKey
    }

    /**
     * Test the property 'bids'
     */
    @Test
    public void bidsTest() {
        // TODO: test bids
    }

    /**
     * Test the property 'asks'
     */
    @Test
    public void asksTest() {
        // TODO: test asks
    }

}
