/*
 * Crossly Buyer API
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.GetSpatialPublicResponseProfileContainers;
import org.openapitools.client.model.GetSpatialPublicResponseProfileItemSize;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for GetSpatialPublicResponseProfile
 */
public class GetSpatialPublicResponseProfileTest {
    private final GetSpatialPublicResponseProfile model = new GetSpatialPublicResponseProfile();

    /**
     * Model tests for GetSpatialPublicResponseProfile
     */
    @Test
    public void testGetSpatialPublicResponseProfile() {
        // TODO: test GetSpatialPublicResponseProfile
    }

    /**
     * Test the property 'categorySlug'
     */
    @Test
    public void categorySlugTest() {
        // TODO: test categorySlug
    }

    /**
     * Test the property 'label'
     */
    @Test
    public void labelTest() {
        // TODO: test label
    }

    /**
     * Test the property 'tagline'
     */
    @Test
    public void taglineTest() {
        // TODO: test tagline
    }

    /**
     * Test the property 'presentation'
     */
    @Test
    public void presentationTest() {
        // TODO: test presentation
    }

    /**
     * Test the property 'itemModelVariants'
     */
    @Test
    public void itemModelVariantsTest() {
        // TODO: test itemModelVariants
    }

    /**
     * Test the property 'itemSize'
     */
    @Test
    public void itemSizeTest() {
        // TODO: test itemSize
    }

    /**
     * Test the property 'containers'
     */
    @Test
    public void containersTest() {
        // TODO: test containers
    }

    /**
     * Test the property 'defaultGroupBy'
     */
    @Test
    public void defaultGroupByTest() {
        // TODO: test defaultGroupBy
    }

    /**
     * Test the property 'defaultSortBy'
     */
    @Test
    public void defaultSortByTest() {
        // TODO: test defaultSortBy
    }

    /**
     * Test the property 'gradedVariant'
     */
    @Test
    public void gradedVariantTest() {
        // TODO: test gradedVariant
    }

}
