/*
 * Crossly Buyer API
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ListCustomersItem
 */
public class ListCustomersItemTest {
    private final ListCustomersItem model = new ListCustomersItem();

    /**
     * Model tests for ListCustomersItem
     */
    @Test
    public void testListCustomersItem() {
        // TODO: test ListCustomersItem
    }

    /**
     * Test the property 'normalizedHandle'
     */
    @Test
    public void normalizedHandleTest() {
        // TODO: test normalizedHandle
    }

    /**
     * Test the property 'platforms'
     */
    @Test
    public void platformsTest() {
        // TODO: test platforms
    }

    /**
     * Test the property 'totalOrders'
     */
    @Test
    public void totalOrdersTest() {
        // TODO: test totalOrders
    }

    /**
     * Test the property 'totalSpent'
     */
    @Test
    public void totalSpentTest() {
        // TODO: test totalSpent
    }

}
